- README.md
- birdhouse/README.md
- birdhouse/config/thredds/catalog.xml.template
- birdhouse/deployment/deploy.sh
- birdhouse/docker-compose.yml
- birdhouse/scripts/backup-restore-solr-index
- vagrant_variables.yml.example
These are all the changes on top of the exact snapshot took from commit https://github.com/Ouranosinc/PAVICS/commit/85350b48ee36253e2301a61c3faa0f49a8b9985b minus the `private-config` folder from the old PAVICS repo (PR https://github.com/Ouranosinc/PAVICS/pull/208).
Mostly it includes all the changes from PAVICS after the commit I transferred here.
You guys should really browse the repo from here https://github.com/bird-house/birdhouse-deploy/tree/changes-since-repo-migration to really see the full future content once this PR is merged.
Can someone also add DavidB as reviewer?
> Changes since repo migration

- birdhouse/common.env
```diff
<     - bokeh==1.4.0
>   - bokeh=1.4.0=py36_0
<   - python=3.7.3=h33d41f4_1
>   - python=3.6.7=h357f687_1006
>   - threddsclient=0.4.2=py_0
<     - xarray==0.13.0
>   - xarray=0.14.1=py_1
<     - dask==2.8.0
>     - dask==2.9.2
<     - xclim==0.12.2
>     - xclim==0.13.0
```
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/34 for more info.
> jupyter: update various packages and add threddsclient

- birdhouse/scripts/migrate-jupyterhub-user-persistence
@davidcaron minor change again, forgot to handle the override.
Forgot in https://github.com/bird-house/birdhouse-deploy/pull/16
> jupyter data migration: handle override of JUPYTERHUB_USER_DATA_DIR

- birdhouse/config/jupyterhub/jupyterhub_config.py.template
Read each commit comments for more infos.
> Increase JupyterHub security

- docs/source/notebooks/README.ipynb
Fixes https://github.com/Ouranosinc/pavics-sdi/issues/151.
Should have been part of PR
https://github.com/bird-house/birdhouse-deploy/pull/16#issuecomment-580799729
(commit
https://github.com/bird-house/birdhouse-deploy/commit/53576cc9d36642c50e4a649ca58fc8339559fd4a).
Dropped the part about " install the `birdy` client locally along with
software to read netCDF files".
> Jupyter README: update to mention personal account and private workspace

- birdhouse/docker-compose.yml
Some noticeable change: https://github.com/Ouranosinc/raven/pull/200
> raven: upgrade to pavics/raven:0.10.0

- birdhouse/common.env
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/37
or commit
https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/8bbb5b472e1ea80f0da54a71ff1c52100c236b23
for more info.
Noticeable Jupyter env changes:
```diff
<   - birdy=v0.6.6=py_0
>     - birdhouse-birdy==0.6.9  (install from Pypi instead of Conda to fix DockerHub failure !)
<   - geopandas=0.7.0=py_1
>   - geopandas=0.6.2=py_0
<   - pandas=1.0.1=py37hb3f55d8_0
>   - pandas=0.25.3=py37hb3f55d8_0
>   - scikit-image=0.16.2=py37hb3f55d8_0
```
> jupyter: update to pavics/workflow-tests:200312 for Raven notebooks

- birdhouse/common.env
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/43 (commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/446b2f1ba3342106e3ad3d2dfe16aece7365c492) for more info.
```diff
<   - geopandas=0.6.2=py_0
>     - geopandas==0.7.0
<   - xarray=0.15.0=py_0
>   - xarray=0.15.1=py_0
<   - owslib=0.19.1=py_0
>   - owslib=0.19.2=py_1
<   - dask-core=2.12.0=py_0
>   - dask-core=2.15.0=py_0
<     - distributed==2.12.0
>     - distributed==2.15.0
<     - xclim==0.14.0
>     - xclim==0.16.0
```
> jupyter: update to pavics/workflow-tests:200427 image

- birdhouse/README.md
- birdhouse/scripts/create-magpie-users
Script to batch create 25 magpie users for issue https://github.com/Ouranosinc/raven/issues/251.  Also useful to delete those test users after it's done.
Found https://github.com/Ouranosinc/Magpie/issues/355 and https://github.com/Ouranosinc/Magpie/issues/354 while writing that script.
@huard @tlogan2000 Just for your info.
> Script to batch create magpie users

- birdhouse/README.md
Updating docs following our discussion.
> README: add suggested deployment layout for infra-as-code

- birdhouse/default.env
See Finch PR for release notes https://github.com/bird-house/finch/pull/138.
Should fix https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/issues/58.
> finch: upgrade to version 0.6.0

- birdhouse/default.env
See Finch PR https://github.com/bird-house/finch/pull/147 for release notes.
Deployed on my dev server, Jenkins run no new errors: http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/900/console
> finch: update to version 0.6.1

- birdhouse/default.env
- birdhouse/docker-compose.yml
See https://github.com/Ouranosinc/raven/compare/v0.10.0...v0.11.1 for change details.
Jupyter env change details: https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/60
Jenkins run (this Jupyter env `pavics/workflow-tests:210201.2` against a devel version of Raven `0.11.1` + `--nbval-lax`) http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/test-nbval-lax-DO_NOT_MERGE/4/console
Only known error:
```
20:25:45  =========================== short test summary info ============================
20:25:45  FAILED pavics-sdi-master/docs/source/notebooks/WMS_example.ipynb::Cell 1
20:25:45  FAILED pavics-sdi-master/docs/source/notebooks/WMS_example.ipynb::Cell 2
20:25:45  FAILED pavics-sdi-master/docs/source/notebooks/WMS_example.ipynb::Cell 3
20:25:45  FAILED …
```
> update Raven and Jupyter env

- birdhouse/components/scheduler/deploy_data_job.env
- birdhouse/components/scheduler/deploy_raven_testdata_to_thredds.env
- birdhouse/components/scheduler/deploy_xclim_testdata_to_thredds.env
- birdhouse/deployment/deploy-data
- birdhouse/deployment/deploy-data-xclim-testdata-to-thredds.yml
- birdhouse/env.local.example
For https://github.com/Ouranosinc/pavics-sdi/pull/201#issuecomment-778329309
Test server https://lvupavicsmaster.ouranos.ca/twitcher/ows/proxy/thredds/catalog/birdhouse/testdata/xclim/catalog.html
Also performed some refactoring to avoid code duplication with the existing Raven testdata sync.
Will sync the following files:
```
created directory /data/datasets/testdata/xclim
cd+++++++++ ./
cd+++++++++ CRCM5/
>f+++++++++ CRCM5/tasmax_bby_198406_se.nc
cd+++++++++ CanESM2_365day/
>f+++++++++ CanESM2_365day/pr_day_CanESM2_rcp85_r1i1p1_na10kgrid_qm-moving-50bins-detrend_2095.nc
>f+++++++++ CanESM2_365day/tasmax_day_CanESM2_rcp85_r1i1p1_na10kgrid_qm-moving-50bins-detrend_2095.nc
>f+++++++++ CanESM2_365day/tasmin_day_CanESM2_rcp85_r1i1p1_na10kgrid_qm-moving-50bins-detrend_2095.nc
cd+++++++++ …
```
> autodeploy: sync Xclim testdata to Thredds

- birdhouse/components/README.rst
- birdhouse/components/scheduler/renew_letsencrypt_ssl_cert_extra_job.env
- birdhouse/deployment/certbotwrapper
- birdhouse/env.local.example
@nikola-rados Don't hesitate to hit me with more questions.  I do not have many people reviewing my "docs" so far.  Pretty sure there are still "undocumented assumptions" somewhere.
> Update docs about LetsEncrypt SSL auto-renewal

- birdhouse/config/canarie-api/docker_configuration.py.template
- Updated components' version number. 
- Replaced links to githubio docs to readthedocs.
- renderer is provided by THREDDS-WMS. 
- slicer is provided by finch.
> Update canarieAPI doc links

- birdhouse/default.env
Finch release notes: https://github.com/bird-house/finch/pull/176
Jupyter env rebuild: https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/70
Finch update useful to fix the Jenkins failure with new finch `subset.ipynb` notebook.
> finch and jupyter: new version

- birdhouse/default.env
Updates finch's image to just released 0.7.4.
- Updates finch's xclim to 0.26.
- Finch now has improved metadata handling : output's attributes are read from config and ensemble processes's datasets are included in the attributes of the output.
- Ensemble processes now compute meaningful statistics for indicators using day-of-year "units".
> Update to new finch.

- .bumpversion.cfg
- CHANGES.md
- README.rst
Forgot to perform bump2version for the previous PR https://github.com/bird-house/birdhouse-deploy/pull/183
> Bump version: 1.13.12 → 1.13.13

- .bumpversion.cfg
- CHANGES.md
- README.rst
Just fixing missing https://github.com/bird-house/birdhouse-deploy/pull/188 changelog.
> update changelog regarding #188

- .bumpversion.cfg
- CHANGES.md
- README.rst
- birdhouse/docker-compose.yml
Changelog https://github.com/Ouranosinc/raven/blob/master/CHANGES.rst#0142                                                                                                                       
0.14.2
------
* Update to RavenPy 0.7.4 (pin climpred below version 2.1.6)
* Fixed a process-breaking bug in `wps_hydrobasins_shape_selection`
0.14.1
------
* Update to RavenPy 0.7.3 (pin xclim version 0.28.1)
0.14
----
* Update to RavenPy 0.7.2
* Use new OWSlib WFS topological filters
* More informative install documentation
* Upgrade to PyWPS 4.4.5
Jenkins build only known error (`Full_process_example_1.ipynb`):
http://jenkins.ouranos.ca/job/ouranos-staging/job/lvupavicsmaster.ouranos.ca/59/console
> Raven: update to version 0.14.2

- docs/requirements.txt
- fix broken readthedocs build
n/a
n/a
- Relates to:
- https://github.com/readthedocs/readthedocs.org/issues/8741
- https://github.com/CrossNox/m2r2/issues/40 
- and other duplicates...
> fix broken readthedocs build

- CHANGES.md
- birdhouse/default.env
Matching PR to deploy new Jupyter to PAVICS.
See Jupyter build PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/94 for more info.
> jupyter: new version with latest changes

- birdhouse/README.rst
We are having more new contributors and I want to avoid repeating myself.
> README: document release procedure for new contributors

- .bumpversion.cfg
- CHANGES.md
- README.rst
- birdhouse/components/weaver/celery-healthcheck
- birdhouse/components/weaver/config/weaver/weaver.ini.template
- birdhouse/components/weaver/default.env
Update default Weaver version with many long-lasting changes and improvements.
* Docker commands that target `weaver-worker` to start or use `celery` must be adjusted according to how its new CLI
resolves certain global parameters. Since the [celery-healthcheck](./birdhouse/components/weaver/celery-healthcheck)
script uses this CLI, `celery` commands were adjusted to consider those changes. If custom scripts or command
overrides are used to call `celery`, similar changes will need to be applied according to employed Weaver version.
See details in [Weaver 4.15.0 changes](https://github.com/crim-ca/weaver/blob/master/CHANGES.rst#4150-2022-04-20).
* Support OpenAPI-based `schema` field for Process I/O definitions to align with latest *OGC API - Processes* changes.
* Support `Prefer` header …
> adjustments to update weaver 4.20.0 by default

- CHANGES.md
- LICENSE
- birdhouse/README.rst
- birdhouse/env.local.example
* Update list of OS tested
* Framework tests code block not rendering properly
* Fixes https://github.com/bird-house/birdhouse-deploy/issues/312
* Fixes https://github.com/bird-house/birdhouse-deploy/issues/309
* Fixes https://github.com/bird-house/birdhouse-deploy/issues/57
* Fixes https://github.com/bird-house/birdhouse-deploy/issues/53
* Fixes https://github.com/bird-house/birdhouse-deploy/issues/55
* Fixes https://github.com/bird-house/birdhouse-deploy/issues/52
* Update the "Release Instructions" in the README to use `make bump <major|minor|patch>` command instead of directly calling `bump2version` to harmonize with the section "Tagging policy" right above.
> Various documentation updates

- CHANGES.md
- LICENSE
See discussion https://github.com/bird-house/birdhouse-deploy/pull/316#discussion_r1169329913
> LICENCE: update copyright line with year and ownership

- README.rst
Update README badges.
Preview: https://github.com/bird-house/birdhouse-deploy/blob/readme-badges/README.rst
- Add the LICENSE reference and badge
- Add the Zenodo DOI reference and badge
- n/a
- n/a
- n/a
> Update README.rst bades
