birdhouse/docker-compose.yml

Bad backport f8391a2cc4b2ffc3ef57c11add6b0b38643572ba removed the
persistence volume mount.

solr: fix accidental removal of persistence volume mount when backport from previous PAVICS repo

---

birdhouse/scripts/backup-restore-solr-index

The `catalog_search.ipynb`
(https://pavics.ouranos.ca/jupyter/user/public/lab/tree/tutorial-notebooks/catalog_search.ipynb)
notebook was failing with this error:
owslib.wps.WPSException : {'code': 'NoApplicableCode', 'locator': 'None', 'text': 'Process error: method=wps_pavicsearch.py._handler, line=254, msg=Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/pavics_datacatalog-0.6.11-py2.7.egg/pavics_datacatalog/wps_processes/wps_pavicsearch.py", line 251, in _handler\n    output_format=output_format)\n  File "/usr/local/lib/python2.7/dist-packages/pavics/catalog.py", line 973, in pavicsearch\n    r.raise_for_status()\n  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status\n    raise HTTPError(http_error_msg, …

backup solr: should save all of /data/solr, not just the index

---

birdhouse/config/catalog/catalog.cfg.template

Fix magpie connection error like:
```
<ows:ExceptionText>Process error: method=wps_pavicrawler.py._handler, line=146, msg=Traceback (most recent call last):
File &#34;/usr/local/lib/python2.7/dist-packages/pavics_datacatalog-0.6.11-py2.7.egg/pavics_datacatalog/wps_processes/wps_pavicrawler.py&#34;, line 125, in _handler
verify=self.verify)
File &#34;/usr/lib/python2.7/dist-packages/requests/sessions.py&#34;, line 523, in post
return self.request(&#39;POST&#39;, url, data=data, json=json, **kwargs)
File &#34;/usr/lib/python2.7/dist-packages/requests/sessions.py&#34;, line 480, in request
resp = self.send(prep, **send_kwargs)
File &#34;/usr/lib/python2.7/dist-packages/requests/sessions.py&#34;, line 588, in send
r = adapter.send(request, **kwargs)
File …
```

catalog: use public hostname in config when using self-signed SSL behind real SSL from pagekite

---

birdhouse/scripts/migrate-jupyterhub-user-persistence

See PR https://github.com/bird-house/birdhouse-deploy/pull/16
or commit
https://github.com/bird-house/birdhouse-deploy/commit/53576cc9d36642c50e4a649ca58fc8339559fd4a
See the `if os.path.exists` in the `jupyterhub_config.py`:
https://github.com/bird-house/birdhouse-deploy/blob/53576cc9d36642c50e4a649ca58fc8339559fd4a/birdhouse/config/jupyterhub/jupyterhub_config.py.template#L36-L48

jupyter data migration: touch new location else jupyterhub won't bind mount them

---

birdhouse/common.env
birdhouse/config/canarie-api/docker_configuration.py.template
birdhouse/docker-compose.yml
birdhouse/env.local.example
birdhouse/optional-components/README.md
birdhouse/optional-components/canarie-api-full-monitoring/.gitignore
birdhouse/optional-components/canarie-api-full-monitoring/a_demo_override_precedence.py
birdhouse/optional-components/canarie-api-full-monitoring/canarie_api_full_monitoring.py.template
birdhouse/optional-components/canarie-api-full-monitoring/docker-compose-extra.yml
birdhouse/optional-components/canarie-api-full-monitoring/z_demo_only_py_file_are_loaded.wrongsuffix
birdhouse/pavics-compose.sh

Fixes https://github.com/bird-house/birdhouse-deploy/issues/8
The motivation was the need for some quick dashboard for the working state of all the components, not to get more stats.
Right now we bypassing Twitcher, which is not real life, it's not what real users will experience.
This is ultra cheap to add and provide very fast and up-to-date (every minute) result. It's like an always on sanity check that can quickly help debugging any connectivity issues between the components.
It is optional because it assumes all components are publicly accessible.  Might not be the case for everyone.  We can also override the override :D
All components in config/canarie-api/docker_configuration.py.template that do not have public (behind Twitcher) monitoring are added.
Also added Hummingbird and …

Optionally monitor all components behind Twitcher using canarie api

---

birdhouse/deployment/deploy.sh

Each user will have to restart their Jupyter server themselves to get
update.
The original intend of the code was to ensure an up-to-date Jupyter
environment.  But it might be too disruptive for the users.

deploy: do not delete user Jupyter server to avoid breaking user's running jobs

---

birdhouse/config/canarie-api/docker_configuration.py.template

The original query returned the first 10 of a total of 45444.
```sh
$ curl --silent "http://pavics.ouranos.ca:8983/solr/birdhouse/select?q=CMIP5&wt=json" | json_pp | grep numFound
"numFound" : 45444,
```
Since we re-crawled, we have new data and the first 10 entries do not
contain the response we look for anymore.
The new query is much more precise so should prevent this from happening
in the future.
```sh
$ curl --silent "http://pavics.ouranos.ca:8983/solr/birdhouse/select?q=CMIP5&fq=model=CanESM2&fq=experiment:rcp85&wt=json" | json_pp | grep numFound
"numFound" : 10
```
@moulab88 I assume the re-crawl you triggered succeeded finally?

proxy: fix canarie-api solr query not precise enough breaking the monitoring

---

birdhouse/config/catalog/catalog.cfg.template

The `thredds_host` should be the exact prefix of each document url found
in Solr, otherwise it is removed from the search result.
This explains why pavicsearch was returning nothing.
This will fix the `catalog_search.ipynb` notebook that keeps failing on Jenkins.
The typo was introduced in PR
https://github.com/bird-house/birdhouse-deploy/pull/5, commit
https://github.com/bird-house/birdhouse-deploy/commit/83c839178fff170dbcb4c4e0586e67d19b9cfbc5
Edit:
* add "This will fix the `catalog_search.ipynb` notebook that keeps failing on Jenkins."

catalog: fix pavicsearch broken due to typo in config

---

birdhouse/components/scheduler/config.json
birdhouse/components/scheduler/docker-compose-extra.yml
birdhouse/deployment/trigger-deploy-notebook

We do not need to manually deploy the autodeploy mechanism (manually run all the `install-*` stcripts under https://github.com/bird-house/birdhouse-deploy/tree/master/birdhouse/deployment) because the cronjob is also a container so all scripts are always up-to-date.
This is part 1, only the tutorial notebooks auto deployment is migrated, serving as proof-of-concept.  The install script is still left behind.  Will remove all install scripts and add full documentation once all autodeployment are migrated in another PR.
Part of issue https://github.com/bird-house/birdhouse-deploy/issues/27.
It's not immediately obvious but 3 separate containers are being spawned from inside each other, accessing the host docker engine.
* The cronjob runs inside the `scheduler` container, as seen in this PR. …

Autodeploy the autodeploy phase 1: tutorial notebooks only and not enabled by default

---

birdhouse/common.env

This is the matching PR that will deploy the new Jupyter env to PAVICS.  @huard if you merge this PR, it will autodeploy tomorrow.
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/36
or commit
https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/f916beadf8f9056e76ed88a52bdfb221c3ee7fb8
jupyter_bokeh (the extension, not the package) was removed due to this issue https://github.com/bokeh/jupyter_bokeh/issues/93
Era5 Raven notebook PR: https://github.com/Ouranosinc/raven/pull/200
Noticeable  rather large Jupyter env changes:
```diff
<   - birdy=v0.6.5=py_0
>   - birdy=v0.6.6=py_0
<   - bokeh=1.4.0=py36_0
>     - bokeh==2.0.0  # from pip recursive dependencies (we get newer version by not explicitly get from conda !)
<   - esgf-compute-api=2.2.1=py_2
>   - …
```

jupyter: update to pavics/workflow-tests:200309 to add regionmask and salem for Era5 Raven notebooks

---

birdhouse/config/thredds/catalog.xml.template
birdhouse/docker-compose.yml

http://lvupavics-lvu.pagekite.me/twitcher/ows/proxy/thredds/catalog/datasets/catalog.html (only gridded_obs/nrcan.ncml works on my dev server).
Add a new top-level "Datasets" at the same level as the existing "Birdhouse".
The content of the new top-level comes from `/data/ncml` from the host.  For comparison content of existing "Birdhouse" was coming from `/data/datasets`.
Given it's a new top level, I was able to remove WCS and WMS links, now thinking more about this ... I am not sure anymore if I should do this, suggestions?
We should also document somewhere this new "Datasets" top level is for NCML files and regular `.nc` files are still under "Birdhouse".  Let me know where to modify the doc.

Thredds: New "Datasets" top level for NCML files

---

birdhouse/README.md
birdhouse/common.env
birdhouse/config/jupyterhub/custom_templates/login.html.template
birdhouse/config/jupyterhub/jupyterhub_config.py.template
birdhouse/docker-compose.yml
birdhouse/env.local.example
birdhouse/pavics-compose.sh
birdhouse/scripts/migrate-jupyterhub-user-persistence
docs/source/notebooks/README.ipynb

For security reasons, the public demo username and password are not hardcoded anymore.
Compromising of one PAVICS deployment should not compromise all other PAVICS deployments if each deployment use a different password.
The password is set when the public demo user is created in Magpie, see the `birdhouse/README.md` update.
The login banner do not display the public demo password anymore.  If one really want to display the password, can use the top or bottom section of the login banner that is customizable via `env.local`.
Login banner is updated with more notices, please review wording.
Resource limits (only memory limit seems to work with the `DockerSpawner`) is also customizable.
All changes to `env.local` are live after a `./pavics-compose.sh up -d`.
Test server: …

Jupyter: make configurable public demo user name, passwd, resource limit, login banner

---

birdhouse/optional-components/emu/.gitignore
birdhouse/optional-components/emu/docker-compose-extra.yml
birdhouse/optional-components/emu/emu_canarie_api_monitoring.py.template
birdhouse/pavics-compose.sh

Allow to have components that are in a completely separate repo (ex: thunderbird from @nikola-rados) to hook into our PAVICS stack without any code change.  Useful for new birds to test compatibility/integration with PAVICS stack early on in their development cycle.
The architecture was already ready for it, just missing template expansion to be performed on those extra repos.
Just realized Canarie monitoring can be "hooked" in as well, after my work in PR https://github.com/bird-house/birdhouse-deploy/pull/22 so I enable it for Emu for demo.
Tested with both Emu and Thunderbird in our PAVICS stack on my dev server: https://lvupavics-lvu.pagekite.me/canarie/node/service/status

Allow components to be from other extra repos and add Emu to Canarie monitoring

---

birdhouse/config/proxy/conf.d/all-services.include.template
birdhouse/config/proxy/nginx.conf

@tlogan2000 @huard needed for a new test Thredds container for testing Ncml.
Nginx will load 2 extra dirs for extending the services and general
Nginx config.
Dir mount means adding new files is trivial and should refresh update
safer than each file mount.
Sample usage:
```
services:
proxy:
volumes:
- ../../custom-config/proxy/conf.extra-service.d/testthredds:/etc/nginx/conf.extra-service.d/testthredds:ro
- ../../custom-config/proxy/conf.extra.d/genericconfig:/etc/nginx/conf.extra.d/genericconfig:ro
```

proxy: allow other extra components to extend Nginx

---

birdhouse/optional-components/README.md
birdhouse/optional-components/emu/docker-compose-extra.yml
birdhouse/optional-components/testthredds/.gitignore
birdhouse/optional-components/testthredds/catalog.xml.template
birdhouse/optional-components/testthredds/conf.extra-service.d/.gitignore
birdhouse/optional-components/testthredds/conf.extra-service.d/testthredds-service.conf.template
birdhouse/optional-components/testthredds/docker-compose-extra.yml
birdhouse/optional-components/testthredds/entrypointwrapper

Here's the configs for the new testthredds, as an optional component obviously.
Not sure why I've put it in our private config earlier, there's nothing private about this.
Having it here will illustrate/demo the use-case for my earlier PR https://github.com/bird-house/birdhouse-deploy/pull/37 (commit https://github.com/bird-house/birdhouse-deploy/commit/4851a4709327e397b8f4c44ba06f8ea4cf922aa0).
The `REAME.md` changes have more infos.

optional-components: testthredds: 2nd Thredds server for testing purposes

---

birdhouse/docker-compose.yml

Fix following 2 Jenkins failures:
Tested in this Jenkins run http://jenkins.ouranos.ca/job/ouranos-staging/job/lvupavics-lvu.pagekite.me/20/console
```
_________ finch-master/docs/source/notebooks/dap_subset.ipynb::Cell 9 __________
Notebook cell execution failed
Cell 9: Cell outputs differ
Input:
resp = wps.sdii(pr + sub)
out = resp.get(asobj=True)
out.output_netcdf.sdii
Traceback:
mismatch 'text/html'
assert reference_output == test_output failed:
'<pre>&lt;xar...vera...</pre>' == '<pre>&lt;xar...vera...</pre>'
Skipping 350 identical leading characters in diff, use -v to show
m/day
-     cell_methods:   time: mean (interval: 30 minutes)
history:        pr=max(0,pr) applied to raw data;\n[DATE_TIME] ...
+     cell_methods:   time: mean (interval: 30 minutes)
standard_name: …
```

finch: update to 0.5.2

---

Vagrantfile
birdhouse/README.md
birdhouse/config/jupyterhub/jupyterhub_config.py.template
birdhouse/deployment/certbotwrapper
birdhouse/deployment/fix-write-perm
birdhouse/deployment/trigger-deploy-notebook
birdhouse/env.local.example
birdhouse/vagrant-utils/configure-pagekite
birdhouse/vagrant-utils/configure-pavics.sh
birdhouse/vagrant-utils/disk-resize
birdhouse/vagrant-utils/install-docker.sh
birdhouse/vagrant-utils/provision.sh
vagrant_variables.yml.example

Fixes https://github.com/bird-house/birdhouse-deploy/issues/27.
Centos7 support added to Vagrant to reproduce problems found on Medus in PR https://github.com/bird-house/birdhouse-deploy/pull/39 (commit https://github.com/bird-house/birdhouse-deploy/commit/6036dbd5ff072544d902e7b84b5eff361b00f78b):
Problem 1: wget httpS url not working in bash docker image breaking the notebook autodeploy when running under the new scheduler autodeploy: **not reproducible**
Problem 2: all containers are destroyed and recreated when alternating between manually running `./pavics-compose.sh up -d` locally and when the same command is executed automatically by the scheduler autodeploy inside its own container: **not reproducible**
Problem 3: `sysctl: error: 'net.ipv4.tcp_tw_reuse' is an unknown key` on …

vagrant: add centos7 and LetsEncrypt SSL cert support, fix scheduler autodeploy remaining issues

---

birdhouse/deployment/trigger-deploy-notebook

Fixes https://github.com/bird-house/birdhouse-deploy/issues/43
Fail early with any unexpected error to not wipe already deployed notebooks.
Check source dir not empty before wiping dest dir containing already deployed notebooks.
Reduce cleaning verbosity for more concise logging.
To fix this error found in production logs when Github is down today:
```
notebookdeploy START_TIME=2020-04-23T10:01:01-0400
++ mktemp -d -t notebookdeploy.XXXXXXXXXXXX
+ TMPDIR=/tmp/notebookdeploy.ICk70Vto2LaE
+ cd /tmp/notebookdeploy.ICk70Vto2LaE
+ mkdir tutorial-notebooks
+ cd tutorial-notebooks
+ wget --quiet https://raw.githubusercontent.com/Ouranosinc/PAVICS-e2e-workflow-tests/master/downloadrepos
+ chmod a+x downloadrepos
chmod: cannot access ‘downloadrepos’: No such file or directory
+ wget --quiet …
```

Fix notebook autodeploy wipe already deployed notebook when GitHub down.

---

birdhouse/scripts/detect-user-install-in-jupyter-env

Danger of user install explained in script header.
What to do if found is explained in reminder message at end.
@huard  @richardarsenault you both have user install in your respective Jupyter env since the last time we had to hack your env for the Raven demo.
Let me know if you want to wipe all those user install yourself (see message at end of script for how to) or I do it for you.
We just had a new Jupyter env (https://github.com/bird-house/birdhouse-deploy/pull/45 https://github.com/bird-house/birdhouse-deploy/commit/2a5dc1ff2465f5da7a0e248d211be8836e1216fe) so to test this new env properly, you should not have any user installs.
```
arsenault/.home/.local/lib/python3.7/site-packages:
.   birdhouse_birdy-0.6.8.dist-info  geopandas                  imageio                  networkx …
```

add script to detect user install in jupyter env

---

birdhouse/common.env

Raven PR https://github.com/Ouranosinc/raven/pull/266 (commit
https://github.com/Ouranosinc/raven/commit/0763bf52abec1bc0a70927de3a2dc2cc1cf77ec3)
removed salem dependency and replaced with rioxarray.
Also add packages for the
[`custom_climate_portraits`](https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/tree/custom_climate_portraits)
branch  (PR
https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/35).
```diff
>   - bokeh=2.0.1=py37hc8dfbb8_0
<     - bokeh==2.0.2
>   - jupyter_bokeh=2.0.1=py_0
>   - dask=2.15.0=py_0
<   - pandas=0.25.3=py37hb3f55d8_0
>   - pandas=1.0.3=py37h0da4684_1
<     - salem==0.2.4
>   - rioxarray=0.0.26=py_0
>   - geoviews=1.8.1=py_0
>   - h5netcdf=0.8.0=py_0
>   - holoviews=1.13.2=pyh9f0ad1d_0
>   - panel=0.9.5=py_1
>   - …
```

jupyter: update to pavics/workflow-tests:200507

---

birdhouse/common.env

@tlogan2000 matching PR to actually deploy the new Jupyter env to PAVICS.
```diff
<   - dask=2.15.0=py_0
>   - dask=2.17.2=py_0
<     - xclim==0.16.0
>     - xclim==0.17.0
```
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/45 (commit
https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/a93f3b50cc6d108638d232fe9465b2f060e21314)
for more info.

jupyter: updated build and fix for pyviz jupyterlab extension

---

birdhouse/common.env

Matching PR to deploy the new Jupyter image to PAVICS.
Added:
* https://github.com/hadim/jupyter-archive
Download entire folder as archive.
* https://blog.jupyter.org/a-visual-debugger-for-jupyter-914e61716559
* https://github.com/plotly/jupyter-dash
Develop Plotly Dash apps interactively from within Jupyter environments.
```diff
>   - jupyter-archive=0.6.2=py_0
>   - jupyter-dash=0.2.1.post1=py_0
<   - owslib=0.19.2=py_1
>   - owslib=0.20.0=py_0
>   - xeus-python=0.7.1=py37h99015e2_1
```
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/46 (commit
https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/441edde3b381eff7ce82e5a171323b31196553be)
for more info.

jupyter: new image for additional plugins

---

birdhouse/docker-compose.yml

Deploy the new Flyingpigeon 1.6 on PAVICS.
Has been deployed to Medus test environment.
flyingpigeon changelog from release commit
https://github.com/bird-house/flyingpigeon/commit/a6f54ed0c20919485c2420295729e30f914cfa15
(PR https://github.com/bird-house/flyingpigeon/pull/332)
1.6 (2020-06-10)
================
* remove eggshell dependency
* notebooks are part of the test suite
* improved plot processes
* remove mosaic option for subset processes
* polygon subset processes files separately instead of an entire data-set at once
* multiple outputs listed in Metalink output
* update pywps to 4.2.3
* use cruft to keep up-to-date with the cookie-cutter template

flyingpigeon: update to version 1.6

---

birdhouse/config/flyingpigeon/wps.cfg.template

Requested by @nilshempelmann for a soilmoisture data set.
This is a 2G file limit !  I wonder if it is possible to give a URL path and the WPS service will fetch the file itself so we do not have to set such a big file limit.

flyingpigeon: set maxsingleinputsize = 2097152000.0

---

birdhouse/common.env

Corresponding change to deploy the new Jupyter env to PAVICS.
```diff
<   - dask=2.17.2=py_0
>   - dask=2.20.0=py_0
>   - nc-time-axis=1.2.0=py_1
<   - xarray=0.15.1=py_0
>   - xarray=0.16.0=py_0
<     - xclim==0.17.0
>     - xclim==0.18.0
```
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/47
(commit
https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/4e03a674930f0974e13724940eee7a608c2158c0)
for more info.

jupyter: new build and add nc-time-axis

---

birdhouse/config/proxy/nginx.conf

Fixes https://github.com/Ouranosinc/raven/issues/286
"there seems to be a problem with the size of the ncml and the timeout
if I use more than 10-12 years as the historical data. I get a :
"Netcdf: DAP failure" error if I use too many years."
```
________________________________________________________ TestBiasCorrect.test_bias_correction ________________________________________________________
Traceback (most recent call last):
File "/zstore/repos/raven/tests/test_bias_correction.py", line 20, in test_bias_correction
ds = (xr.open_dataset(hist_data).sel(lat=slice(lat + 1, lat - 1),lon=slice(lon - 1, lon + 1), time=slice(dt.datetime(1991,1,1), dt.datetime(2010,12,31))).mean(dim={"lat", "lon"}, keep_attrs=True))
File "/home/lvu/.conda/envs/raven/lib/python3.7/site-packages/xarray/core/commo …
```

proxy: increase timeout for reading a response from the proxied server

---

birdhouse/common.env

See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/48 for more detailed info.
Deployed to Medus for testing (as regular PAVICS image, not the devel image).  @aulemahal let me know if violin plot is finally working.
```diff
<   - hvplot=0.6.0=pyh9f0ad1d_0
>   - hvplot=0.5.2=py_0
<   - dask=2.20.0=py_0
>   - dask=2.22.0=py_0
<   - geopandas=0.8.0=py_1
>   - geopandas=0.8.1=py_0
<   - pandas=1.0.5=py37h0da4684_0
>   - pandas=1.1.0=py37h3340039_0
<   - matplotlib=3.2.2=1
>   - matplotlib=3.3.0=1
<   - numpy=1.18.5=py37h8960a57_0
>   - numpy=1.19.1=py37h8960a57_0
<   - cryptography=2.9.2=py37hb09aad4_0
>   - cryptography=3.0=py37hb09aad4_0
<   - python=3.7.6=h8356626_5_cpython
>   - python=3.7.8=h6f2ec95_1_cpython
<   - nbval=0.9.5=py_0
>   - …
```

jupyter: new update image with hvplot pinned to older version for violin plot

---

birdhouse/default.env

Matching PR to deploy the new jupyter image to PAVICS.
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/50 (commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/02333bfa11931f4a0b7c9607b88904bd063bed70)
that built the new image with the detailed change vs the previous image.
Add handcalcs https://github.com/connorferster/handcalcs/ and unpin hvplot
since pinning did not solve violin plot issue, see this comment
https://github.com/bird-house/birdhouse-deploy/pull/63#issuecomment-668270608
Successful Jenkins build
http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/periodic-rebuild-and-add-handcalcs/1/console
```diff
>     - handcalcs==0.8.1
<     - xclim==0.18.0
>     - xclim==0.19.0
<   - hvplot=0.5.2=py_0
>   - …
```

jupyter: new updated image with new handcalcs package

---

birdhouse/components/scheduler/renew_letsencrypt_ssl_cert_extra_job.env
birdhouse/deployment/certbotwrapper
birdhouse/deployment/deploy.sh
birdhouse/deployment/triggerdeploy.sh
birdhouse/env.local.example
birdhouse/pavics-compose.sh
birdhouse/vagrant-utils/configure-pavics.sh
vagrant_variables.yml.example

Auto-renew LetsEncrypt SSL certificate leveraging the cron jobs of the "scheduler" component.  Meaning this feature is self-contained in the PAVICS stack, no dependency on the host's cron jobs.
Default behavior is to attempt renewal everyday.  `certbot` client in `renew` mode will not hit LetsEncrypt server if renewal is not allowed (not within 1 month of expiry) so this should not put too much stress on LetsEncrypt server.  However, this gives us 30 retry opportunities (1 month) if something is wrong on the first try.
All configs are centralized in `env.local`, easing reproducibility on multiple deployments of PAVICS and following infra-as-code.
User can still perform the renewal manually by calling `certbotwrapper` directly. User is not forced to enable the "scheduler" component but …

Auto-renew LetsEncrypt SSL certificate

---

birdhouse/default.env

Matching PR to deploy new Jupyter env from PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/52 (commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/18c8397ff30c9ba4b9f56896df4c898c7e9a356e).
Deployed to https://medus.ouranos.ca/jupyter/ for testing.
```diff
>   - clisops=0.3.1=pyh32f6830_1
<     - xclim==0.19.0
>   - xclim=0.20.0=py_0
<   - xarray=0.16.0py_0
>   - xarray=0.16.1=py_0
<   - dask=2.26.0=py_0
>   - dask=2.27.0=py_0
<   - fiona=1.8.13=py37h0492a4a_1
>   - fiona=1.8.17=py37ha3d844c_0
<   - gdal=3.0.4=py37h4b180d9_10
>   - gdal=3.1.2=py37h518339e_2
<   - jupyter_server=0.1.1=py37_0
>   - jupyter_server=1.0.1=py37hc8dfbb8_0
>     - jupyternotify==0.1.15
>     - pytest-tornasync==0.6.0.post2
```
See PR above for full changes.

jupyter: new build for new xclim with fix for missing clisops dependency

---

birdhouse/README.md
birdhouse/components/scheduler/deploy_raven_testdata_to_thredds.env
birdhouse/deployment/deploy-data
birdhouse/deployment/deploy-data-raven-testdata-to-thredds.yml
birdhouse/deployment/deploy-data.config.sample.yml
birdhouse/env.local.example
birdhouse/vagrant-utils/configure-pavics.sh

Leveraging the cron daemon of the scheduler component, sync Raven testdata to Thredds for Raven tutorial notebooks.
Activation of the pre-configured cronjob is via `env.local` as usual for infra-as-code.
New generic `deploy-data` script can clone any number of git repos, sync any number of folders in the git repo to any number of local folders, with ability to cherry-pick just the few files needed (Raven testdata has many types of files, we only need to sync `.nc` files to Thredds, to avoid polluting Thredds storage `/data/datasets/testdata/raven`).
Limitation of the first version of this `deploy-data` script:
* Do not handle re-organizing file layout, this is a pure sync only with very limited rsync filtering for now (tutorial notebooks deploy from multiple repos, need re-organizing the …

Sync Raven testdata to Thredds for Raven tutorial notebooks

---

birdhouse/default.env

Matching PR to deploy the new Jupyter image to PAVICS.
Deployed to https://medus.ouranos.ca/jupyter/ for testing.  This one has python 3.8, might worth some manual testing.
```diff
<   - python=3.7.8=h6f2ec95_1_cpython
>   - python=3.8.6=h852b56e_0_cpython
<   - xclim=0.20.0=py_0
>   - xclim=0.21.0=py_0
<   - dask=2.27.0=py_0
>   - dask=2.30.0=py_0
<   - rioxarray=0.0.31=py_0
>   - rioxarray=0.1.0=py_0
>   - memory_profiler=0.58.0=py_0
```
More info, see PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/53 (commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/f07f1657ed13a0ed92854c5d01f9d3ed785e870d)

jupyter: new image for python 3.8, new xclim and memory_profiler

---

birdhouse/README.md
birdhouse/config/canarie-api/docker_configuration.py.template
birdhouse/config/jupyterhub/jupyterhub_config.py.template
birdhouse/env.local.example
birdhouse/optional-components/README.md
birdhouse/scripts/bootstrap-instance-for-testsuite
birdhouse/scripts/bootstrap-testdata
birdhouse/scripts/create-magpie-authtest-user
birdhouse/scripts/create-magpie-users
birdhouse/scripts/trigger-pavicscrawler

@MatProv is building an automated pipeline that will provision and deploy a full PAVICS stack and run our Jenkins test suite for each PR here.
So each time his new fresh instance comes up, there are a few steps to perform for the Jenkins test suite to pass.  Those steps are captured in `scripts/bootstrap-instance-for-testsuite`.  @MatProv please call this script, do not perform each steps yourself so any future changes to those steps will be transparent to your pipeline.  A new optional components was also required, done in PR https://github.com/bird-house/birdhouse-deploy/pull/92.
For security reasons, Jupyterhub will block the test user to login since its password is known publicly.
Each step are also in their own script so can be assembled differently to prepare the fresh instance if …

Prepare fresh deployment for automated tests

---

birdhouse/scripts/create-magpie-authtest-user

Changed `authtest` user password, since magpie 3.1.0 now requires 12 characters password

changed authtest user password

---

birdhouse/config/jupyterhub/jupyterhub_config.py.template
birdhouse/default.env
birdhouse/docker-compose.yml
birdhouse/env.local.example

The google drive extension for JupyterLab requires a settings file containing the clientid of the project created in developers.google.com, which give authorization to use google drive.
This PR's role is to include this file in the birdhouse configs.
Matching PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/54 (commit https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/commit/5d5a9aa2251386378406efb5b414b3aa6db0b37e) for the new image with 4 new extensions: jupytext, jupyterlab-google-drive, jupyter_conda and jupyterlab-git
Matching PR https://github.com/Ouranosinc/pavics-sdi/pull/185 for documention about the new extensions.

jupyter: new image with 4 new extensions

---

birdhouse/components/monitoring/docker-compose-extra.yml
birdhouse/config/jupyterhub/jupyterhub_config.py.template
birdhouse/scripts/bootstrap-instance-for-testsuite
birdhouse/scripts/check-instance-ready

monitoring: prevent losing stats when VM auto start from a power failure
check-instance-ready: new script to smoke test instance (use in `bootstrap-instance-for-testsuite` for our automation pipeline).
jupyter: add CATALOG_USERNAME and anonymous to blocked_users list for security
They are not real Jupyter users and their password is known.
See config/magpie/permissions.cfg.template that created those users.
Tested:
```
[W 2020-11-20 13:25:18.924 JupyterHub auth:487] User 'admin-catalog' blocked. Stop authentication
[W 2020-11-20 13:25:18.924 JupyterHub base:752] Failed login for admin-catalog
[W 2020-11-20 13:49:18.069 JupyterHub auth:487] User 'anonymous' blocked. Stop authentication
[W 2020-11-20 13:49:18.070 JupyterHub base:752] Failed login for anonymous
```

Various small fixes

---

birdhouse/config/postgres/postgres-setup.sh

Before fix:
```sh
$ ./pavics-compose up -d
(...)
Restarting proxy ... done
Waiting for postgres database connection
postgres:5432 - accepting connections
psql: FATAL:  database "postgres-pavics" does not exist
```
After fix:
```sh
Restarting proxy ... done
Waiting for postgres database connection
postgres:5432 - accepting connections
```
Root cause:
This commit
https://github.com/Ouranosinc/PAVICS/commit/7ffc6317a280486261bed1240369b890a743f5a8
changed
```diff
birdhouse/config/postgres/credentials.env
@@ -1,3 +0,0 @@
POSTGRES_USER=pavics
POSTGRES_DB=pavics
POSTGRES_PASSWORD=qwerty
```
to
```diff
birdhouse/config/postgres/credentials.env.template
@@ -0,0 +1,3 @@
POSTGRES_USER=${POSTGRES_PAVICS_USERNAME}
POSTGRES_PASSWORD=${POSTGRES_PAVICS_PASSWORD}
POSTGRES_DB=pavics
```
and so …

pavics-compose.sh: fix annoying postgres false error

---

birdhouse/deployment/deploy-data
birdhouse/deployment/deploy-data.config.sample.yml

Script `deploy-data` was previously introduced in PR https://github.com/bird-house/birdhouse-deploy/pull/72 to deploy any files from any git repos to the local host it runs.
Now it grows the ability to run commands from the git repo it just pulls.
Being able to run commands open new possibilities:
* post-processing after files from git repo are deployed (ex: advanced file re-mapping)
* execute up-to-date scripts from git repos (PR https://github.com/bird-house/birdhouse-deploy-ouranos/pull/2)
Combining this `deploy-data` with the `scheduler` component means we have a way for cronjobs to automatically always execute the most up-to-date version of any scripts from any git repos.
@tlogan2000, @huard FYI this was required for the GEPS forecasts project.

Add ability to execute post actions for deploy-data script

---

birdhouse/deployment/deploy-data-raven-testdata-to-thredds.yml

For automated raven testdata sync at https://pavics.ouranos.ca/twitcher/ows/proxy/thredds/catalog/birdhouse/testdata/raven/catalog.html
Will add the following new files from raven-testdata repo.  All existing are still there.
```
cd+++++++++ eccc_forecasts/                                                                                                                           
>f+++++++++ eccc_forecasts/geps_watershed.nc                                                                                                          
cd+++++++++ era5/                                               
>f+++++++++ era5/tas_pr_20180101-20180108.nc                                               
cd+++++++++ raven-routing-sample/                                                   
>f+++++++++ …
```

deploy raven testdata to thredds: switch to new repo raven-testdata

---

birdhouse/default.env

Matching PR to deploy the new Jupyter env in PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/56 to PAVICS.
```diff
>   - cfgrib=0.9.8.5=pyhd8ed1ab_0
<   - clisops=0.3.1=pyh32f6830_1
>   - clisops=0.4.0=pyhd3deb0d_0
<   - dask=2.30.0=py_0
>   - dask=2020.12.0=pyhd8ed1ab_0
<   - owslib=0.20.0=py_0
>   - owslib=0.21.0=pyhd8ed1ab_0
<   - xarray=0.16.1=py_0
>   - xarray=0.16.2=pyhd8ed1ab_0
<   - xclim=0.21.0=py_0
>   - xclim=0.22.0=pyhd8ed1ab_0
<   - jupyter_conda=3.4.1=pyh9f0ad1d_0
>   - jupyter_conda=4.1.0=hd8ed1ab_1
```

jupyter: update to version 201214

---

birdhouse/scripts/bootstrap-testdata

For `docs/source/notebooks/canopex.ipynb` in commit
https://github.com/Ouranosinc/raven/commit/e50d3f3a969aff2f250538f4778aca57740d35e9
File has been renamed to https://github.com/Ouranosinc/raven/blob/766a288d282b99f097d0d2e0e4a31adf25b8d72c/docs/source/notebooks/Running_HMETS_with_CANOPEX_dataset.ipynb
See matching PR https://github.com/Ouranosinc/raven/pull/338

bootstrap-testdata: add more for Raven

---

birdhouse/README.rst
birdhouse/config/proxy/nginx.conf

Fix this timeout error in some Raven notebooks:
```
HTTPError: 504 Server Error: Gateway Time-out for url:
https://pavics.ouranos.ca/twitcher/ows/proxy/raven/wps
```
This is just a work-around since something is very wrong on our
production host Boreas (a physical host with 128G ram and 48 logical cpu).
During the test, Boreas was having this "load average: 6.35, 5.90,
4.33".  For its hardware specs, it is basically idle.
The increased timeout was not needed for my test VM (10G ram, 2 cpu),
medus.ouranos.ca (physical host with 16G ram, 16 logical cpu) and
hirondelle.crim.ca (VM with 32G ram, 8 cpu).
Should fix https://github.com/Ouranosinc/raven/issues/362 and fix https://github.com/Ouranosinc/raven/issues/357.
Ping @moulab88 to take a look at Boreas.  Just a wild guess, is it due for a …

proxy: increase timeout since raven can take lots of time to process requests

---

birdhouse/components/scheduler/renew_letsencrypt_ssl_cert_extra_job.env

To avoid cutting connection daily since the proxy is restarted during renewal attempt.

cronjob: attempt LetsEncrypt SSL renewal weekly instead of daily

---

birdhouse/default.env

Matching PR to deploy https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/61 to PAVICS.
For regridding notebook, see https://github.com/Ouranosinc/pavics-sdi/pull/201#issuecomment-778329309.
```diff
>   - xesmf=0.5.2=pyhd8ed1ab_0
<   - owslib=0.21.0=pyhd8ed1ab_0
>   - owslib=0.23.0=pyhd8ed1ab_0
<   - cftime=1.3.1=py37h6323ea4_0
>   - cftime=1.4.1=py37h902c9e0_0
<   - dask=2021.1.1=pyhd8ed1ab_0
>   - dask=2021.2.0=pyhd8ed1ab_0
<   - rioxarray=0.1.1=pyhd8ed1ab_0
>   - rioxarray=0.2.0=pyhd8ed1ab_0
```

jupyter: update to version 210216 for xESMF

---

birdhouse/config/jupyterhub/jupyterhub_config.py.template
birdhouse/default.env
birdhouse/docker-compose.yml
birdhouse/env.local.example

While the [`README.ipynb`](https://github.com/bird-house/birdhouse-deploy/blob/master/docs/source/notebooks/README.ipynb) provided by `birdhouse-deploy` is good, it does not quite fit our needs at PCIC. This PR allows users to configure their own `README` for Jupyterhub.
- Adds `JUPYERHUB_README` as configuration option in the appropriate spots

Configurable Jupyterhub README

---

birdhouse/scripts/bootstrap-testdata

Need those new testdata on hosts other than `pavics.ouranos.ca` to run Jenkins end-to-end test suite against those hosts.
For notebook https://github.com/Ouranosinc/pavics-sdi/blob/bbe3061dceb98688e9fd58836fbc50992ee31568/docs/source/notebooks/regridding.ipynb
See PR https://github.com/Ouranosinc/pavics-sdi/pull/201

bootstrap-testdata: new testdata for pavics-sdi regridding notebook

---

birdhouse/default.env

Require PR https://github.com/bird-house/birdhouse-deploy/pull/131 for extra testdata for the new regridding notebook.
Regridding notebook will also need to be adjusted for some output to pass Jenkins test suite, PR https://github.com/Ouranosinc/pavics-sdi/pull/206.
Nbval escape regex also needed for the regridding notebook, PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/63
See Finch changelog in PR https://github.com/bird-house/finch/pull/158
Passing Jenkins build http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/update-nbval-sanitize-config-for-pavics-sdi-regridding-notebook/10/console

finch: update to 0.7.0

---

birdhouse/config/jupyterhub/jupyterhub_config.py.template

Because of the missing `c` definition, the whole file gets flagged wish masks away other potential errors. 
Adding its definition limits the error only to that line add is ignored away. 
This allowed to identify other issues such as mismatching spaces/tabs that have been fixed. 
Everyone that worked on the file tagged for validation

add 'get_config()' call to limit python error to that line

---

birdhouse/deployment/certbotwrapper
birdhouse/deployment/deploy.sh
birdhouse/deployment/trigger-deploy-notebook
birdhouse/scripts/backup-datavolume.sh
birdhouse/scripts/backup-jupyterhub-notebooks.sh

Pin bash tag so it is reproducible (previously it was more or less reproducible since we always ensure "latest" tag).
Avoid the following error:
```
+ docker pull bash
Using default tag: latest
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Avoid docker pull since pull rate limit on dockerhub

---

birdhouse/components/scheduler/renew_letsencrypt_ssl_cert_extra_job.env
birdhouse/env.local.example
birdhouse/vagrant-utils/configure-pavics.sh

Found accidentally when manually harmonizing `env.local` produced by
Vagrant with the template `env.local.example`.
Vagrant automatic provisioning does the right thing to activate
`renew_letsencrypt_ssl_cert_extra_job.env` after the redefined
SSL_CERTIFICATE but if someone like me, manually re-order this, it
will break.
Fix the follow error, SSL_CERTIFICATE was set to /home/vagrant/certkey.pem.
```
+ '[' -s /tmp/tmp_certbotwrapper_ssl_cert.pem ]
+ diff /home/vagrant/certkey.pem /tmp/tmp_certbotwrapper_ssl_cert.pem
diff: can't stat '/home/vagrant/certkey.pem': No such file or directory
+ '[' 0 -eq 0 ]
+ cp -v /tmp/tmp_certbotwrapper_ssl_cert.pem /home/vagrant/certkey.pem
cp: can't create '/home/vagrant/certkey.pem': No such file or directory
```

doc LetsEncrypt SSL renew job should be sourced after SSL_CERTIFICATE in env.local

---

birdhouse/config/canarie-api/docker_configuration.py.template

The Canarie API complains that `stats` are up but don't return the correct response. I assume it's because I changed the monitoring key to reflect the actual content.

reverted name of monitoring routes to original

---

birdhouse/default.env

Matching PR to deploy the new Jupyter env to PAVICS.
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/68
for more info.
```diff
<   - clisops=0.5.1=pyhd3deb0d_0
>   - clisops=0.6.3=pyh44b312d_0
<   - xclim=0.23.0=pyhd8ed1ab_0
>   - xclim=0.25.0=pyhd8ed1ab_0
>   - ostrich=0.1.2=h2bc3f7f_0
>   - raven=0.1.1=h2bc3f7f_0
<     - ravenpy==0.2.3  # from pip
>   - ravenpy=0.3.1=py37_0  # from conda
>   - aiohttp=3.7.4=py37h5e8e339_0
<   - roocs-utils=0.1.5=pyhd3deb0d_1
>   - roocs-utils=0.3.0=pyh6c4a22f_0
<   - cf_xarray=0.4.0=pyh44b312d_0
>   - cf_xarray=0.5.1=pyh44b312d_0
<   - rioxarray=0.2.0=pyhd8ed1ab_0
>   - rioxarray=0.3.1=pyhd8ed1ab_0
<   - xarray=0.16.2=pyhd8ed1ab_0
>   - xarray=0.17.0=pyhd8ed1ab_0
<   - geopandas=0.8.2=pyhd8ed1ab_0
>   - …
```

jupyter: update for new clisops, xclim, ravenpy

---

birdhouse/scripts/bootstrap-testdata

For notebook https://github.com/bird-house/finch/blob/e2298701dcd20b24dae021c666ebb684d3640b4b/docs/source/notebooks/subset.ipynb
To fix error in `docker logs finch`:
```
OSError: [Errno -102] NetCDF: Can't read file: b'https://lvupavicsdev.ouranos.ca/twitcher/ows/proxy/thredds/dodsC/birdhouse/testdata/xclim/NRCANdaily$
nrcan_canada_daily_tasmin_1990.nc'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/opt/conda/envs/finch/lib/python3.9/site-packages/pywps/app/Process.py", line 248, in _run_process
self.handler(wps_request, wps_response)  # the user must update the wps_response.
File "/code/finch/processes/wps_base.py", line 42, in _handler_wrapper
raise ProcessError(f"Finch failed with {err!r}") …
```

testdata: new test file for new finch subset.ipynb

---

birdhouse/config/finch/wps.cfg.template
birdhouse/config/jupyterhub/jupyterhub_config.py.template
birdhouse/config/raven/wps.cfg.template
birdhouse/default.env
birdhouse/docker-compose.yml

Raven release notes PR https://github.com/Ouranosinc/raven/pull/374 + https://github.com/Ouranosinc/raven/pull/382
Jupyter env update PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/71
Other fixes:
* Fix intermittent Jupyter spawning error by doubling various timeouts config (it's intermittent so hard to test so we are not sure which ones of timeout fixed it)
* Fix Finch and Raven "Broken pipe" error when the request size is larger than default 3mb (bumped to 100mb) (fixes https://github.com/Ouranosinc/raven/issues/361 and Finch related comment https://github.com/bird-house/finch/issues/98#issuecomment-811230388)
* Lower chance to have "Max connection" error for Finch and Raven (bump parallelprocesses from 2 to 10). In prod, the server has the CPU needed to run 10 …

Update raven and jupyter env for raven demo

---

birdhouse/config/magpie/providers.cfg.template
birdhouse/docker-compose.yml
birdhouse/env.local.example
birdhouse/optional-components/README.rst
birdhouse/optional-components/all-public-access/all-public-access-magpie-permission.cfg
birdhouse/optional-components/secure-thredds/docker-compose-extra.yml
birdhouse/optional-components/secure-thredds/secure-access-magpie-permission.cfg
birdhouse/scripts/create-magpie-users

Strike II of this original PR https://github.com/bird-house/birdhouse-deploy/pull/107.
Matching notebook fix https://github.com/Ouranosinc/pavics-sdi/pull/218
Performed test upgrade on staging (Medus) using prod (Boreas) Magpie DB, everything went well and Jenkins passed (http://jenkins.ouranos.ca/job/ouranos-staging/job/medus.ouranos.ca/80/parameters/).  This Jenkins build uses the corresponding branch in https://github.com/Ouranosinc/pavics-sdi/pull/218 and with `TEST_MAGPIE_AUTH` enabled.
Manual upgrade migration procedure:
1. Save `/data/magpie_persist` folder from prod `pavics.ouranos.ca`: `cd /data; tar czf magpie_persist.prod.tgz magpie_persist`
2. scp `magpie_persist.prod.tgz` to `medus`
3. login to `medus`
4. `cd /path/to/birdhouse-deploy/birdhouse`
3. `./pavics-compose.sh down` …

Magpie upgrade strike II

---

birdhouse/config/proxy/conf.d/all-services.include.template
birdhouse/default.env
birdhouse/env.local.example
birdhouse/pavics-compose.sh

For each org to have their own custom homepage.
Existing default to redirect to JupyterHub login page is preserved for when no custom homepage is required.
See matching PR for deploying Ouranos custom homepage https://github.com/bird-house/birdhouse-deploy-ouranos/pull/11.
Test server: https://lvupavics.ouranos.ca
Fixes https://github.com/Ouranosinc/PAVICS-landing/issues/20.

proxy: allow homepage (location /) to be configurable

---

birdhouse/docker-compose.yml

Bump default log retention to 500m instead of 2m, more suitable for prod
Forgot to push during PR https://github.com/bird-house/birdhouse-deploy/pull/152.
- Bump default log retention to 500m instead of 2m, more suitable for prod

bump default log retention to 500m instead of 2m, more suitable for prod

---

birdhouse/docker-compose.yml

This updates raven to 0.13.0, which corresponds to the work done in these PRs:
* https://github.com/Ouranosinc/raven/pull/384
* https://github.com/Ouranosinc/raven/pull/385
* https://github.com/Ouranosinc/raven/pull/386
This was needed following the upgrade to RavenPy 0.5

Update to raven 0.13.0

---

birdhouse/README.rst
birdhouse/config/magpie/magpie.ini.template
birdhouse/default.env
birdhouse/docker-compose.yml
birdhouse/optional-components/secure-thredds/secure-access-magpie-permission.cfg
birdhouse/scripts/create-magpie-authtest-user
birdhouse/scripts/create-magpie-users

~should be tested after #151 for iterative updates~
Update directly to latest Magpie (3.8 -> ... -> 3.12)
Updates magpie 3.12 (see [CHANGES](https://github.com/Ouranosinc/Magpie/blob/master/CHANGES.rst#3120-2021-05-11) for details)
Changes: 
- Applies relevant modifications to configuration following `gunicorn` update in Magpie
(docker image uses `pserve` CLI instead of directly calling `gunicorn`, which requires a small adjustment of `host`/`bind` value in the [magpie.ini](https://github.com/bird-house/birdhouse-deploy/blob/master/birdhouse/config/magpie/magpie.ini.template) config)
- Provides improved webhook configuration and implementations (for eventual [cowbird](https://github.com/Ouranosinc/cowbird))
- Providers headers `WWW-Authenticate` and `Location-When-Unauthenticated` when …

magpie 3.x + gunicorn bind

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support.md
.github/PULL_REQUEST_TEMPLATE.md
.github/config.yml
.github/labeler.yml
.github/workflows/greetings.yml
.github/workflows/label.yml

Improve CI templates and labelling of issues for the repo.
- Adds issue Github templates, for each of: documentation, (question) support, bug and feature request.
- Update formatting of existing PR template 
- Add auto-labeler action that will apply labels onto matched modified files by PRs. 
- Auto-label opened issues (with above templates) with corresponding labels.
n/a
- Resolves #158 
see auto-label already in action just below :arrow_down:

 issue/PR templates & auto-labels

---

birdhouse/deployment/deploy.sh
birdhouse/deployment/triggerdeploy.sh

The new code added with [this merge](https://github.com/bird-house/birdhouse-deploy/commit/d90765acabe248e65c4899929fbe37a9e8661643) created a new bug for the autodeploy job.
From the autodeploy job's log : 
```
triggerdeploy START_TIME=2021-05-13T14:00:03+0000
Error: DEPLOY_DATA_JOB_SCHEDULE not set
```
If the `AUTODEPLOY_NOTEBOOK_FREQUENCY` variable is not set in the `env.local` file, it would create the error above.
The variable is set in the `default.env` file, in case it is not defined in the `env.local`, and is then used for the new env file from pavics-jupyter-base [here](https://github.com/bird-house/pavics-jupyter-base/blob/1f81480fe90e0a110f0320c6d6cb17f73b657733/scheduler-jobs/deploy_data_pavics_jupyter.env#L15).
The error happens because the `default.env` was not called in the …

Bugfix for autodeploy job

---

birdhouse/default.env

To deploy the new Jupyter env to PAVICS.
Given it's an incremental build, these are the only differences:
```diff
>   - intake-geopandas=0.2.4=pyhd8ed1ab_0
>   - intake-thredds=2021.6.16=pyhd8ed1ab_0
>   - intake-xarray=0.5.0=pyhd8ed1ab_0
```
See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/76.

jupyter: update for raven notebooks

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env
birdhouse/deployment/trigger-deploy-notebook

- Notebook deployment: allow to specify required branch for any tutorial notebook repos in `env.local`
Example: set `WORKFLOW_TESTS_BRANCH` and any other notebook deploy config like `PAVICS_LANDING_BRANCH` in `env.local`
- jupyter: minor update to add `unzip` package                                                                                                   
`unzip` needed to test PAVICS-landing notebooks under Jenkins.  No other package updates.
To support this PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/79

Notebook deployment: allow to specify required branch for any tutorial notebook repos in env.local

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/config/thredds/catalog.xml.template

We have some `csv` files we want to make available on `THREDDS`. 
- Adds extra file type to `catalog.xml` filter
- None
- None (although I could make one then edit this)
This is a very small change, and I wasn't sure it was worth it to create (and maintain) a fork just for this. Furthermore, I couldn't really find a good way to make this more dynamic without adding a bunch of unnecessary complexity.

Add csv to filter

---

CHANGES.md
birdhouse/default.env

See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/84 for more info.
```diff
<   - ravenpy=0.5.2=pyh7f9bfb9_0
>   - ravenpy=0.6.0=pyh1bb2064_2
<   - xclim=0.27.0=pyhd8ed1ab_0
>   - xclim=0.28.0=pyhd8ed1ab_0
<   - birdy=v0.8.0=pyh6c4a22f_0
>   - birdy=v0.8.0=pyh6c4a22f_1
<   - cf_xarray=0.5.2=pyh6c4a22f_0
>   - cf_xarray=0.6.0=pyh6c4a22f_0
<   - cftime=1.4.1=py37h902c9e0_0
>   - cftime=1.5.0=py37h6f94858_0
<   - dask=2021.6.0=pyhd8ed1ab_0
>   - dask=2021.7.0=pyhd8ed1ab_0
<   - nc-time-axis=1.2.0=py_1
>   - nc-time-axis=1.3.1=pyhd8ed1ab_2
<   - rioxarray=0.4.1.post0=pyhd8ed1ab_0
>   - rioxarray=0.5.0=pyhd8ed1ab_0
<   - numpy=1.20.3=py37h038b26d_1
>   - numpy=1.21.1=py37h038b26d_0
<   - pandas=1.2.4=py37h219a48f_0
>   - pandas=1.2.5=py37h219a48f_0
<   - …
```

jupyter: update for RavenPy-0.6.0, Xclim-0.28.0 and latest of everything else

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

See PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/85 for more info.
```diff
<   - jupyterlab=2.2.9=pyhd8ed1ab_0
>   - jupyterlab=3.1.0=pyhd8ed1ab_0
<   - jupyterlab_server=1.2.0=py_0
>   - jupyterlab_server=2.6.1=pyhd8ed1ab_0
<   - jupyter-archive=2.2.0=pyhd8ed1ab_0
>   - jupyter-archive=3.0.1=pyhd8ed1ab_0
<   - jupyter_bokeh=2.0.4=pyhd8ed1ab_0
>   - jupyter_bokeh=3.0.2=pyhd8ed1ab_0
<   - jupyterlab-git=0.24.0=pyhd8ed1ab_0
>   - jupyterlab-git=0.31.0=pyhd8ed1ab_0
<   - nbdime=2.1.0=py_0
>   - nbdime=3.1.0=pyhd8ed1ab_0
<     - nbresuse==0.4.0
>   - nbresuse=0.4.0=pyhd8ed1ab_0
>   - nbclassic=0.3.1=pyhd8ed1ab_1
>   - jupyterlab-system-monitor=0.8.0=pyhd8ed1ab_1
>   - jupyter-resource-usage=0.5.1=pyhd8ed1ab_0
>   - jupyterlab-topbar=0.6.1=pyhd8ed1ab_2
> …
```

jupyter: update for JupyterLab v3, fix memory monitor display and RavenPy-0.7.0

---

CHANGES.md
birdhouse/config/magpie/magpie.ini.template
birdhouse/config/twitcher/twitcher.ini.template
birdhouse/default.env

Applies the same changes as #174 (cache settings) but disable Twitcher caching (Magpie caching already disabled) 
This is in order to validate that cache settings are applied and tests suite can run successfully with cache disabled, 
to isolate that sporadic errors seen in #174 are related to enabled cache.
- Added cache settings of `MagpieAdapter` through Twitcher (intended to improve response times, but disabled in this PR).
- Update Magpie/Twitcher version 3.14.0
- Unique user email in Magpie is enforced, see changelog for how to find them and update the conflicted values before the upgrade.  Otherwise the upgrade will break.
- Undo resolution of [DAC-296 Twitcher performance issue](https://www.crim.ca/jira/browse/DAC-296) since caching now …

Twitcher/Magpie upgrade and Cache settings off

---

CHANGES.md
birdhouse/config/magpie/magpie.ini.template
birdhouse/config/twitcher/twitcher.ini.template
birdhouse/default.env

Improve response times of Twitcher by caching repeated permission ACL and service resolution in Magpie.
- Added cache settings of `MagpieAdapter` through Twitcher to improve response times.
Since caching will occur, any permission update could take up to the configured expire time to take effect. 
The expire time could be increased or reduced based on usage and how often user/resource/permissions actually change.
If immediate/force update validation of permissions must be done, `Cache-Control: no-cache` header can be used in the request.
- Resolves [DAC-296](https://www.crim.ca/jira/browse/DAC-296)
- Relates to  bird-house/twitcher#97
- Related new stress test https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/74

Mapie/Twticher Cache Settings

---

.bumpversion.cfg
CHANGES.md
README.rst

Following  merge of pull request #182 from bird-house/cache-settings-off
Applies the same changes as #174 (cache settings) but disable Twitcher caching explicitly (Magpie caching already disabled).
This is in order to validate that cache settings are applied and tests suite can run successfully with cache disabled, 
to isolate that sporadic errors seen in #174 are related to enabled cache.
- Added cache settings of `MagpieAdapter` through Twitcher (intended to improve response times, but disabled in this PR).
- Update Magpie/Twitcher version 3.14.0
- Unique user email in Magpie 3.13.0 is enforced, see birdhouse-deploy changelog for how to find them and update the conflicted values before the upgrade.  Otherwise the upgrade will break. See …

Bump version: 1.13.14 → 1.14.0

---

birdhouse/config/twitcher/twitcher.ini.template

Re-enables the caching feature of Twitcher that was disabled temporarily in #182 
- Twitcher request caching=on
n/a
- Resolves https://github.com/Ouranosinc/Magpie/issues/433

re-enable caching feature of twitcher

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

Bokeh png export now also works.
Other noticeable changes:
```diff
<   - ravenpy=0.7.0=pyh1bb2064_0
>   - ravenpy=0.7.4=pyh7f9bfb9_0
<   - xclim=0.28.0=pyhd8ed1ab_0
>   - xclim=0.28.1=pyhd8ed1ab_0
>   - geckodriver=0.29.1=h3146498_0
>   - selenium=3.141.0=py37h5e8e339_1002
>   - nested_dict=1.61=pyhd3deb0d_0
>   - paramiko=2.7.2=pyh9f0ad1d_0
>   - scp=0.14.0=pyhd8ed1ab_0
>   - s3fs=2021.8.1=pyhd8ed1ab_0
<   - pandas=1.3.1=py37h219a48f_0
>   - pandas=1.2.5=py37h219a48f_0
<   - owslib=0.24.1=pyhd8ed1ab_0
>   - owslib=0.25.0=pyhd8ed1ab_0
<   - cf_xarray=0.6.0=pyh6c4a22f_0
>   - cf_xarray=0.6.1=pyh6c4a22f_0
<   - rioxarray=0.5.0=pyhd8ed1ab_0
>   - rioxarray=0.7.0=pyhd8ed1ab_0
<   - climpred=2.1.4=pyhd8ed1ab_0
>   - climpred=2.1.5.post1=pyhd8ed1ab_0
<   - dask=2021.7.1=pyhd8ed1ab_0
>   - …
```

jupyter: update for new RavenPy and other new packages

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

Changelog https://github.com/bird-house/finch/blob/master/CHANGES.rst#075-2021-09-07
```
0.7.5 (2021-09-07)
Update to xclim 0.27
Added empirical_quantile_mapping process calling xclim.sdba.EmpiricalQuantileMapping.
Update to PyWPS 4.4.5
```
Matching Finch notebook fix: https://github.com/bird-house/finch/pull/201
Matching PAVICS-SDI notebook fix: https://github.com/Ouranosinc/pavics-sdi/pull/229

Update finch to 0.7.5

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/components/weaver/docker-compose-extra.yml
birdhouse/docker-compose.yml

Move `mongodb` network to `mongodb` image directly and update `phoenix`/`weaver` images accordingly.
- Apply ``mongodb`` network to ``mongodb`` image in order to allow ``phoenix`` to properly reference it.
- Remove ``mongodb`` definition from ``./components/weaver`` since the extended ``mongodb`` network is already provided.
- n/a
- Resolves https://github.com/bird-house/birdhouse-deploy/pull/114#discussion_r740666666

fix mongodb network

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/scripts/extract-jupyter-users-from-magpie-db

Extract Jupyter users from Magpie DB so we can send announcements to all Jupyter users.
Sample output:
```
$ ./scripts/extract-jupyter-users-from-magpie-db  > /tmp/out
+ echo SELECT email,user_name FROM users ORDER BY email
+ docker exec -i postgres-magpie psql -U postgres-magpie magpiedb
$ cat /tmp/out
email          |   user_name
------------------------+---------------
admin-catalog@mail.com | admin-catalog
admin@mail.com         | admin
anonymous@mail.com     | anonymous
authtest@example.com   | authtest
(4 rows)
```

scripts: add `extract-jupyter-users-from-magpie-db`

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/scripts/bootstrap-instance-for-testsuite
birdhouse/scripts/bootstrap-testdata
birdhouse/scripts/create-magpie-authtest-user
birdhouse/scripts/trigger-pavicscrawler
birdhouse/vagrant-utils/install-docker.sh

Found when trying to bring up the new production host for PAVICS.
`install-docker.sh`: fix to work with users with sudo priviledge.  Before it needed user `root`.
Other comments in scripts are due to new Magpie in PR https://github.com/bird-house/birdhouse-deploy/pull/107.

Minor fix to `install-docker.sh` and comment update for other scripts due to Magpie upgrade

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/components/weaver/.gitignore

- Add missing ``config/canarie-api/weaver_config.py`` entry to ``.gitignore`` of ``./components/weaver``
that is generated from the corresponding template file.
- n/a
- Resolves https://github.com/bird-house/birdhouse-deploy/pull/114#discussion_r741553883

ignore generated weaver_config under canarie-api

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

- New component version Finch:0.7.7
Revert "added SENTRY_ENV environment variable" by @matprov in #213
Refresh notebooks by @Zeitsperre in https://github.com/bird-house/finch/pull/201
Add SENTRY_ENV param by @matprov in https://github.com/bird-house/finch/pull/203
Multiple rcps for ensemble processes by @aulemahal in https://github.com/bird-house/finch/pull/202
Remove bugging drop after geoserver upgrade by @aulemahal in https://github.com/bird-house/finch/pull/207
Update to xclim 0.31 by @aulemahal in https://github.com/bird-house/finch/pull/209
Fix xarray, dask and gunicorn related hang by @cjauvin in https://github.com/bird-house/finch/pull/204
run load() before switching to single-threaded scheduler by @huard in https://github.com/bird-house/finch/pull/211
Add …

Update Finch to v0.7.7

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/components/weaver/config/weaver/weaver.ini.template
birdhouse/components/weaver/default.env
birdhouse/components/weaver/docker-compose-extra.yml

- Upgrade default `Weaver` version to [4.5.0](https://github.com/crim-ca/weaver/blob/master/CHANGES.rst#450-2021-11-25)   (from [4.2.1](https://github.com/crim-ca/weaver/blob/master/CHANGES.rst#421-2021-10-20)) for new features and fixes.
- Adds support of `X-WPS-Output-Context` header to define the WPS output nested directory (for user context).
- Adds support of `X-Auth-Docker` header to define a private Docker registry authentication token when the 
referenced Docker image in the deployed Application Package requires it to fetch it for Process execution. 
- Require `MongoDB==5.0` Docker image for Weaver's database.
- Fixes related to handling `dismiss` operation of job executions and retrieval of their results.
- Fixes related to fetching remote files and …

bump weaver 4.5.0 and relevant mongodb changes

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

Quebec gouvernment has shutdown its website due to this vulnerability so it's pretty serious
(https://montrealgazette.com/news/quebec/quebec-government-shutting-down-websites-report).
Jenkins with only known intermittent failure
http://jenkins.ouranos.ca/job/PAVICS-e2e-workflow-tests/job/master/1367/console
Thredds release notes: https://github.com/Unidata/thredds/releases
https://www.oracle.com/security-alerts/alert-cve-2021-44228.html
**Oracle Security Alert Advisory - CVE-2021-44228 Description**
This Security Alert addresses CVE-2021-44228, a remote code execution
vulnerability in Apache Log4j. It is remotely exploitable without
authentication, i.e., may be exploited over a network without the need for a
username and password.
Due to the severity of this vulnerability and the …

thredds: update for Log4j Vulnerability CVE-2021-44228

---

.bumpversion.cfg
CHANGES.md
README.rst

Forgot to bump version in previous PR https://github.com/bird-house/birdhouse-deploy/pull/229 "Matching PR to deploy new Jupyter to PAVICS.".
See Jupyter build PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/94 for more info.

Bump version: 1.18.2 → 1.18.3

---

.bumpversion.cfg
CHANGES.md
README.rst
Vagrantfile
birdhouse/vagrant-utils/configure-pagekite
birdhouse/vagrant-utils/install-docker.sh
vagrant_variables.yml.example

RockyLinux 8 is the successor to Centos 7.
Centos 8 has become like a "RHEL 8 beta" than the equivalent of RHEL 8.
RockyLinux 8 is the new equivalent of RHEL 8, following the original spirit of the Centos project.
More info at https://rockylinux.org/about.

Vagrant: Support RockyLinux

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

Deploy new Jupyter env from PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/95 on PAVICS.
Detailed changes can be found at https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/95.
```diff
<   - xclim=0.31.0=pyhd8ed1ab_0
>   - xclim=0.32.1=pyhd8ed1ab_0
<   - ravenpy=0.7.5=pyhff6ddc9_0
>   - ravenpy=0.7.8=pyh8a188c0_0
<   - python=3.7.12=hb7a2778_100_cpython
>   - python=3.8.12=hb7a2778_2_cpython
<   - vcs=8.2.1=pyh9f0ad1d_0
<   - numpy=1.21.4=py37h31617e3_0
>   - numpy=1.21.5=py38h87f13fb_0
<   - xarray=0.20.1=pyhd8ed1ab_0
>   - xarray=0.20.2=pyhd8ed1ab_0
<   - rioxarray=0.8.0=pyhd8ed1ab_0
>   - rioxarray=0.9.1=pyhd8ed1ab_0
<   - cf_xarray=0.6.1=pyh6c4a22f_0
>   - cf_xarray=0.6.3=pyhd8ed1ab_0
<   - gdal=3.3.2=py37hd5a0ba4_2
>   - …
```

Jupyter: update Jupyter env for latest XClim, RavenPy and all packages

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

Magpie: update `magpie` service from [3.19.1](https://github.com/Ouranosinc/Magpie/tree/3.19.1) to [3.21.0](https://github.com/Ouranosinc/Magpie/tree/3.21.0).
- Update *WFS*, *WMS* and *WPS* related services to properly implement the relevant *Permissions* and *Resources*
according to their specific implementation details. For example, *GeoServer*-based *WMS* implementation supports
*Workspaces* and additional operations that are not offered by standard *OGC*-based *WMS*. Some of these
implementation specific operations can be taken advantage of with improved *Permissions* and *Resources* resolution.
- Add multi-*Resource* effective access resolution for *Services* that support it.
For example, accessing multiple *Layers* under a permission-restricted *WFS* with …

update magpie 3.19.1 -> 3.21.0

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/components/weaver/celery-healthcheck
birdhouse/components/weaver/config/weaver/weaver.ini.template
birdhouse/components/weaver/default.env
birdhouse/components/weaver/docker-compose-extra.yml

Weaver: update `weaver` component from [4.5.0](https://github.com/crim-ca/weaver/tree/4.5.0) to [4.12.0](https://github.com/crim-ca/weaver/tree/4.12.0).
- Adds `WeaverClient` and *Weaver CLI*. Although not strictly employed by the platform itself to offer *Weaver* as a
service, these can be employed to interact with *Weaver* using Python or shell commands, providing access to all 
WPS *birds* offered by the platform using the common [OGC API - Processes][ogcapi-proc] interface through 
[Weaver Providers](https://pavics-weaver.readthedocs.io/en/latest/processes.html#remote-provider).
- Adds [Vault](https://pavics-weaver.readthedocs.io/en/latest/processes.html#vault) functionality allowing temporary
and secure storage to upload files for single-use process …

update weaver 4.5.0 -> 4.12.0

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

Please include a summary of the changes and which issues are fixed. 
Please also include relevant motivation and context. 
List any dependencies that are required for this change.
- Finch: update `finch` component 
from [0.7.7](https://github.com/bird-house/finch/releases/tag/v0.7.7)
to [0.8.2](https://github.com/bird-house/finch/releases/tag/v0.8.2)
Relevant Changes:
- v0.8.0
- Add hourly_to_daily process
- Avoid annoying warnings by updating birdy (environment-docs)
- Upgrade to clisops 0.8.0 to accelerate spatial averages over regions. 
- Upgrade to xesmf 0.6.2 to fix spatial averaging bug not weighing correctly cells with varying areas. 
- Update to PyWPS 4.5.1 to allow the creation of recursive directories for outputs.
- v0.8.2
- Add ``geoseries_to_netcdf`` process, converting a …

Update finch to v0.8.2

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

Deploy new Jupyter env from PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/101 on PAVICS.
Detailed changes can be found at https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/101.
```diff
>   - pre-commit=2.17.0=py38h578d9bd_0
>   - xlrd=2.0.1=pyhd8ed1ab_3
<   - xclim=0.32.1=pyhd8ed1ab_0
>   - xclim=0.34.0=pyhd8ed1ab_0
<   - cfgrib=0.9.9.1=pyhd8ed1ab_1
>   - cfgrib=0.9.10.1=pyhd8ed1ab_0
<   - cftime=1.5.1.1=py38h6c62de6_1
>   - cftime=1.6.0=py38h3ec907f_0
<   - intake-xarray=0.5.0=pyhd8ed1ab_0
>   - intake-xarray=0.6.0=pyhd8ed1ab_0
<   - pandas=1.3.5=py38h43a58ef_0
>   - pandas=1.4.1=py38h43a58ef_0
<   - regionmask=0.8.0=pyhd8ed1ab_1
>   - regionmask=0.9.0=pyhd8ed1ab_0
<   - rioxarray=0.9.1=pyhd8ed1ab_0
>   - rioxarray=0.10.3=pyhd8ed1ab_0
<   - …
```

jupyter env: new xlrd, pre-commit, pin dask, distributed, cf_xarray, latest of everything else

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

PR to deploy new Finch releases in https://github.com/bird-house/finch/pull/233 on PAVICS.
See the Finch PR for more info.
Finch release notes:
0.8.3 (2022-04-21)
------------------
* Preserve RCP dimension in ensemble processes, even when only RCP is selected.
* Pin ``dask`` and ``distributed`` at ``2022.1.0``, see https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/issues/100

finch: new release for dask performance problem

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/config/jupyterhub/jupyterhub_config.py.template
birdhouse/default.env

Deploy new Jupyter env from PR https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/105 on PAVICS.
Detailed changes can be found at https://github.com/Ouranosinc/PAVICS-e2e-workflow-tests/pull/105.
Dask dashboard no manual URL mangling required:
"Render with Panel" button works:
```diff
>   - dask-labextension=5.2.0=pyhd8ed1ab_0
>   - jupyter-panel-proxy=0.2.0a2=py_0
>   - jupyter-server-proxy=3.2.1=pyhd8ed1ab_0
<     - handcalcs==1.4.1
<   - xclim=0.34.0=pyhd8ed1ab_0
>   - xclim=0.36.0=pyhd8ed1ab_0
<   - cf_xarray=0.6.3=pyhd8ed1ab_0
>   - cf_xarray=0.7.2=pyhd8ed1ab_0
<   - clisops=0.8.0=pyh6c4a22f_0
>   - clisops=0.9.0=pyh6c4a22f_0
<   - pandas=1.4.1=py38h43a58ef_0
>   - pandas=1.3.5=py38h43a58ef_0
<   - rioxarray=0.10.3=pyhd8ed1ab_0
>   - …
```

jupyter env: new build for new XClim and to get Dask dashboard and Panel server app to work

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/deployment/deploy-data

When `deploy-data` is used by the `scheduler` component, it is run as
`root`.  This new env var will force the rsync process to run as a regular user to
follow security best practice to avoid running as root when not needed.
Note that the `git checkout` step done by `deploy-data` is still run as root.
This is because `deploy-data` is currently still run as root so it can
execute `docker` commands (ex: spawning the `rsync` command above in its own
docker container).
To fix this limitation, the regular user inside the `deploy-data` container
need to have docker access inside the container and outside on the host at
the same time.  If we make that regular user configurable so the script
`deploy-data` is generic and can work for any organisations, this is tricky
for the moment so will have to …

deploy-data: new env var DEPLOY_DATA_RSYNC_USER_GRP to avoid running cronjobs as root

---

.bumpversion.cfg
.gitignore
CHANGES.md
README.rst
birdhouse/components/weaver/config/magpie/adapter_hooks.py
birdhouse/components/weaver/config/magpie/config.yml.template
birdhouse/components/weaver/config/magpie/weaver_hooks.py
birdhouse/components/weaver/docker-compose-extra.yml
birdhouse/default.env
birdhouse/docker-compose.yml

When a process is deployed on Weaver, the user that deployed it (provided they had permission to do so), will automatically receive the necessary permissions to obtain access to its description and execution of jobs with it.
The process will be visible only by the deploying user (and admins) until it gets shared/published with other users/groups with the appropriate permissions applied in Magpie.
- Adds Magpie response hook that will create necessary permissions for user onto its deployed Weaver process.
- n/a
**Note**: only commits after https://github.com/bird-house/birdhouse-deploy/pull/247/commits/e661ef269bdeba5d8a503bfbc5727b8c8082964e can be used to see only the diff of *this* PR omitting other dependencies.
- Resolves [DAC-206 - *user …

Auto user permissions creation over its deployed process

---

CHANGES.md
birdhouse/components/weaver/config/magpie/adapter_hooks.py
birdhouse/components/weaver/config/magpie/config.yml.template
birdhouse/components/weaver/config/magpie/weaver_hooks.py
birdhouse/components/weaver/docker-compose-extra.yml
birdhouse/default.env

Prepare magpie/twitcher/weaver requests hooks for WPS outputs in user workspace directory 
- When a job is run on weaver while being logged in, the output results will be nested under a user-workspace directory rather than at the root of WPS outputs. 
- n/a
- Depends on: 
- https://github.com/Ouranosinc/Magpie/pull/517  (Magpie [3.25.0](https://github.com/Ouranosinc/Magpie/tree/3.25.0))
- https://github.com/bird-house/twitcher/pull/114  (Twitcher [0.7.0](https://github.com/bird-house/twitcher/tree/v0.7.0))

magpie/twitcher/weaver requests hooks for WPS outputs in user workspace

---

.gitignore
CHANGES.md
birdhouse/components/weaver/config/magpie/adapter_hooks.py
birdhouse/components/weaver/config/magpie/config.yml.template
birdhouse/components/weaver/config/magpie/weaver_hooks.py
birdhouse/components/weaver/docker-compose-extra.yml
birdhouse/default.env
birdhouse/docker-compose.yml

- Processes returned by `Weaver` during listing will be filtered with read permissions to those processes.
- Update `Magpie` to 3.26.0
- n/a
- Depends on https://github.com/bird-house/birdhouse-deploy/pull/244
- Depends on https://github.com/Ouranosinc/Magpie/pull/519 (Magpie 3.26.0)
- Addresses [DAC-178](https://crim-ca.atlassian.net/browse/DAC-178).
Permissions applied for `anonymous` group and `authtest` user respectively (only `weaver` service matters here). 
Responses from `weaver` placed behind twitcher with the magpie filtering hook of this PR.
Response for `admin`:
Response for `authtest` user:
Response for `anonymous` (not logged in):

add magpie/twticher response hook for filtering weaver processes

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/default.env

PR to deploy this new Finch to PAVICS.  
Will need notebook fix for `climex.ipynb` and `subset-user-input.ipynb` in another PR.
Finch release notes:
0.9.2 (2022-07-19)
==================
* Fix Finch unable to startup in the Docker image.
0.9.1 (2022-07-07)
==================
* Avoid using a broken version of ``libarchive`` in the Docker image.
0.9.0 (2022-07-06)
==================
* Fix use of ``output_name``, add ``output_format`` to xclim indicators.
* Change all outputs to use ``output`` as the main output field name (instead of ``output_netcdf``).
* Updated to xclim 0.37:
- Percentile inputs of xclim indicators have been renamed with generic names, excluding an explicit mention to the target percentile.
- In ensemble processes, these percentiles can now be chosen through …

finch: new release for new Xclim

---

docs/requirements.txt
docs/source/conf.py

Need to use `sphinx-mdinclude` since the newer version `mistune` do not work with `m2r2` on ReadTheDocs.  We needed the newer version of `mistune` for a security fix.
Error on ReadTheDocs  https://readthedocs.org/projects/birdhouse-deploy/builds/17578562/
```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/birdhouse-deploy/envs/251/lib/python3.6/site-packages/sphinx/cmd/build.py", line 276, in build_main
args.pdb)
File "/home/docs/checkouts/readthedocs.org/user_builds/birdhouse-deploy/envs/251/lib/python3.6/site-packages/sphinx/application.py", line 222, in __init__
self.setup_extension(extension)
File "/home/docs/checkouts/readthedocs.org/user_builds/birdhouse-deploy/envs/251/lib/python3.6/site-packages/sphinx/application.py", line 400, in …
```

Remove m2r2 in favour of sphinx-mdinclude

---

.bumpversion.cfg
CHANGES.md
README.rst
Vagrantfile
birdhouse/config/geoserver/.gitignore
birdhouse/config/geoserver/Dockerfile
birdhouse/config/geoserver/entrypointwrapper
birdhouse/default.env
vagrant_variables.yml.example

See plugin documentation at https://docs.geoserver.org/2.19.x/en/user/community/metadata/index.html
Related to issue https://github.com/Ouranosinc/pavics-sdi/issues/234
Add new "Metadata" tab in Layer Edit page:

GeoServer: enable metadata-plugin for modifying layer metadata, including bulk modifications

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/config/canarie-api/docker_configuration.py.template

Platform version reported by ``canarie`` service was not kept up to date with tagged versions.
- Add bumpversion config entry to update references on future bump.
- n/a

fix bumpversion not updating server config version reference

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/config/canarie-api/docker_configuration.py.template
birdhouse/docker-compose.yml

LetsEncrypt older root certificate "DST Root CA X3" expired on September 30,
2021, see https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
All the major browsers and OS platform has previously added the new root
certificate "ISRG Root X1" ahead of time so the transition to the new
root certificate is seemless for all clients.
Python `requests` package bundle their own copy of known root
certificates and is late to add this new root cert "ISRG Root X1".  Had
it automatically fallback to the OS copy of the root cert bundle, this
would have been seemless.
The fix is to force `requests` to use the OS copy of the root cert bundle.
Fix for this error:
```
$ docker exec proxy python -c "import requests; requests.request('GET', 'https://lvupavicsmaster.ouranos.ca/geoserver'
> …
```

canarie-api: fix unable to verify LetsEncrypt SSL certs

---

.bumpversion.cfg
CHANGES.md
README.rst
birdhouse/components/weaver/default.env
birdhouse/config/canarie-api/docker_configuration.py.template

While working on https://github.com/crim-ca/weaver/pull/455, I found some errors parsing I/O during remote WPS processes execution. 
When the stack is evaluated with `weaver` component enabled, we can see that the test process `ncdump` on WPS `hummingbird` fails (process description works, but its execution fails at some point). For example, see failures in `pavics-sdi-master/docs/source/notebook-components/weaver_example.ipynb` output in https://github.com/bird-house/birdhouse-deploy/pull/253#issuecomment-1208753167.
<details>
<summary>Test Failure Details</summary>
<pre>
<code>
20:03:05  ---------------------------------------------------------------------------
20:03:05  AssertionError                            Traceback (most recent call last)
20:03:05  Input In [10], in <cell line: …

bump weaver to 4.22.0 by default - fixes for WPS remote provider execution

---

CHANGES.md
birdhouse/config/jupyterhub/jupyterhub_config.py.template
birdhouse/default.env
birdhouse/env.local.example

Fix to support JupyterHub image selection names that use the `<name>:<version>` format. 
Initially, we were only displaying the name of the images on the JupyterHub page, but we added the version to give more information to the user. This requires the adjustment found in this PR, since we rely on those values to find a corresponding directory to mount when starting the image. The directory should only be named using the `name` part, and should exclude the `version`. 
For example, if we display an option `eo-crim:0.3.0` on the JupyterHub selection page, the image used to start JupyterLab should mount the directory `eo-crim`, which should contain its corresponding tutorial notebooks.
I also added some more comments to clarify the relationship between the names displayed on the JupyterHub …

support display image names with version on jupyterhub

---

CHANGES.md
birdhouse/components/jupyterhub/default.env

Previously, JupyterHub's `MagpieAuthenticator` class treated the email address entered into the username field as the username itself. This led to a mismatch between the username in JupyterHub and the username in Magpie.
To resolve this, we update the JupyterHub docker image to a version where this bug is fixed. 
See https://github.com/Ouranosinc/jupyterhub/pull/26 and https://github.com/Ouranosinc/Magpie/issues/598 for reference.
- Update jupyterhub to version 4.0.2-20240117
- Resolves https://github.com/Ouranosinc/Magpie/issues/598 

Allow users to log in to Jupyterhub with their email address

---

CHANGES.md
birdhouse/env.local.example

`JUPYTERHUB_CONFIG_OVERRIDE` was disconnected from its sample code.
This is just a comment fix.  Zero chance to introduce any regressions.
I won't tag it upon merging this PR.

env.local.example: fix `JUPYTERHUB_CONFIG_OVERRIDE` comment section

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support.md

No change to the platform. Only GitHub issue templates assignees are modified.
- Change GitHub issue templates assignees for latest organization maintainers.
- Add CODEOWNERS file for default PR reviewers with same organization maintainers.
- n/a
- 
- n/a
- n/a

update GitHub issue+pr templates assignees

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

Remove explicit `birdhouse_skip_ci: true` from PR template
(note: this one above is left in there on purpose for the current PR)
When opening PRs, developers could easily leave in the `` comment about CI, causing the CI to falsely detect the condition when parsing the PR description, and ending up skipping it. Change the format of the sentence to avoid the false detection.
- Edit PR template.
- n/a
- n/a

remove explicit `birdhouse_skip_ci: true` from PR template

---

CHANGES.md
birdhouse/components/geoserver/service-config.json.template

The `/geoserver` endpoint redirects to the HTML web view of the service.
Fix the indicated media-type of `type` for that endpoint in the service definition.
- fix content-type of GeoServer `service-config.json.template`
- n/a
- n/a

fix content-type of geoserver service-config.json.template

---

CHANGES.md
docs/requirements.txt

Issue seen on https://readthedocs.org/projects/birdhouse-deploy/builds/24109903/
`AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'`
- docs: Fix version of `sphinx-mdinclude` to address incompatible `docutils` operation under ReadTheDocs Sphinx build.
- n/a
- See [docutils 0.21 changes](https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-21-2024-04-09).
- See issue [sphinx-mdinclude#47](https://github.com/omnilib/sphinx-mdinclude/issues/47)     and PR [sphinx-mdinclude#55](https://github.com/omnilib/sphinx-mdinclude/pull/55).

fix readthedocs build

---

CHANGES.md
birdhouse/components/weaver/post-docker-compose-up

Debugging cause of diff in final output of https://github.com/Ouranosinc/pavics-sdi/blob/master/docs/source/notebook-components/weaver_example.ipynb
Built on top of https://github.com/bird-house/birdhouse-deploy/pull/439
- New component version Weaver: 5.1.1
- Fixes to Weaver WSP provider registration retry logic.

weaver: bump version to 5.1.0 + debug notebook output

---

CHANGES.md
birdhouse/deployment/deploy-data-xclim-testdata-to-thredds.yml

This PR updates the cloning of the xclim-testdata repo to reflect structural changes.
- Adjusts the location of the xclim-testdata data folder
- https://github.com/Ouranosinc/xclim-testdata/pull/29
- https://github.com/Ouranosinc/xclim/pull/1889

Adapt to the new xclim-testdata structure

---

docs/source/conf.py

Fix docs build invalid `intersphinx_mapping`.
- fix docs
- n/a
- Fix error as seen in https://readthedocs.org/projects/birdhouse-deploy/builds/25570203/

fix docs build invalid `intersphinx_mapping`

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template to avoid default regex self-match when copy-pasted to merge commit message.
Use roundabout comment description to avoid matching the regex.
- CI maintenance, PR template
- n/a
- Fix PR not triggering CI.

Update PR template to avoid default regex self-match when copy-pasted to merge commit message

---

docs/source/index.rst
docs/source/migration_guide.rst

This is a documentation change only. 
The migration guide is hidden in the CHANGES.md file which is fine if you know where to look for it but is easy to miss otherwise. This PR creates a new migration guide file that will be included in the docs. This file contains a copy of the version 2.4 migration guide (translated from markdown to reStructuredText syntax) and all future migration guides should be added here so that they are more visible to users.
None
None

add migration guide to docs

---

CHANGES.md
bin/birdhouse

Update description of the `configs` subcommand to better describe it.
The description when calling `bin/birdhouse -h` now matches the description when calling `bin/birdhouse configs -h`
help string update
None
https://github.com/bird-house/birdhouse-deploy/pull/478#discussion_r1852852846

Fix help string description for `bin/birdhouse configs` command

---

CHANGES.md
birdhouse/env.local.example

The recommended public share folders in the `env.local.example` file create a conflict with the default `PUBLIC_WORKSPACE_WPS_OUTPUTS_SUBDIR` path when both are enabled and mounted on a Jupyterlab container. This change updates the recommended paths for the public share folders to avoid this conflict and adds a warning helping users to avoid this conflict.
Note: the conflict arises when `PUBLIC_WORKSPACE_WPS_OUTPUTS_SUBDIR` is mounted to a container as read-only volume and then Jupyterhub tries to mount the public share folder within that volume. Since the parent volume is read-only, the second volume mount fails.
None, documentation only
None
- Resolves #392 …

Jupyterhub: update recommended paths for public share folders

---

CHANGES.md

Document reasoning for pulling in new Thredds v5, even with minor issues in previous PR https://github.com/bird-house/birdhouse-deploy/pull/413.

CHANGES: document reasoning for pulling in new Thredds v5, even with minor issues

---

CHANGES.md
birdhouse/components/proxy/conf.d/frontend.conf.template

Nginx requires a resolver to be explicity defined when using `proxy_pass` with a variable in the argument passed to `proxy_pass`. This resolver is defined explicitly for the https server block but not for the http server block.
This adds the explicit resolver for the http server block as well so that `proxy_pass` works when called using using http URLs as well.
- Bug fix (only relevant for http URLs, ie. non-production environments)
- None

Add resolver for http nginx configuration

---

CHANGES.md
birdhouse/birdhouse-compose.sh
birdhouse/components/scheduler/default.env
birdhouse/default.env
birdhouse/env.local.example
birdhouse/optional-components/local-dev-test/pre-docker-compose-up.include

Sets the default compose command to `docker compose` using the new `DOCKER_COMPOSE` environment variable. This uses compose v2 by default (instead of v1 which is very old and has been deprecated for a while). For backwards compatibility, you can set `DOCKER_COMPOSE=docker-compose` in the local environment file to use the previous default.
- If you do not have a version of docker that has a compose subcommand, you will have to set `DOCKER_COMPOSE=docker-compose` in env.local
This means that new installations will not need to download a separate `docker-compose` binary.

deprecate docker-compose default command

---

CHANGES.md
birdhouse/birdhouse-compose.sh

Code related to the solr catalog in the `birdhouse-compose.sh` file has been deprecated for a while and is not currently usable with the current stack anyway so it is removed
Also there is commented out old code that relates to the presence of an SSL certificate which is not use and no longer relevant as of version [2.7.0](https://github.com/bird-house/birdhouse-deploy/releases/tag/2.7.0).
- cleanup unused code
- None

remove deprecated catalog crawler code

---

bin/birdhouse

Minor fix. Add missing `-p` option required to example command. 

fix birdhouse example command

---

birdhouse/README.rst

See the "Note" heading in the TOC under 
https://birdhouse-deploy.readthedocs.io/en/latest/deployment.html#deployment
- Patch the header that displays weirdly in the generated docs
- n/a
- n/a

Patch the header that displays weirdly in the generated docs

---

birdhouse/read-configs.include.sh

Logged errors in case of required variable include a `$`, leading to this kind of display: 
```sh
ERROR:    Required variable $ALERTMANAGER_SMTP_SERVER is not set. Check env.local file.
```
This gives the impression that something was not parsed or interpreted correctly. 
- remove the prefixed `$` from the variable in the log message, if any is applied, as in the case of `VAR` definitions having literal `$<VAR>`.
- n/a
- Relates to https://github.com/bird-house/birdhouse-deploy/issues/514

remove `$` from logged error variable

---

CHANGES.md
birdhouse/birdhouse-compose.sh
birdhouse/default.env

Handle template generation with more lenient error handling and allow override when they occur.
- Improve handling of `.template` files generation
* Add `BIRDHOUSE_COMPOSE_TEMPLATE_FORCE` variable that allows enforcing the generation of the `.template` files
instead of only when compose `up` command is passed by default.
* Add automatic removal of empty directories conflicting with `.template` destinations. 
This occurs only if a `docker compose` command ran early, and it generated volume mount directories to the
yet non-existing files.
* Add logs when template generation occurs, is skipped, or edge case directories are removed.
- n/a
- Resolves https://github.com/bird-house/birdhouse-deploy/issues/508 …

improved template file generation

---

CHANGES.md
birdhouse/components/jupyterhub/default.env
birdhouse/env.local.example

This PR updates the Jupyter env image with several new versions of dependencies. The Anaconda environment has been overhauled to rely more on native Anaconda packages and to remove many old/incompatible packages.
**The version in this PR has not yet been bumped**
_Not adding things here under breaking/non-breaking, as I'm not certain what constitutes either type of change (though I would tend towards these being breaking changes for scientists)_
- Updates the Jupyter environment for PAVICS to py311-250423
- Anaconda channels now include `nodefaults` and `fortiers` (for `fstd2nc` library).
- Many obsolete and incompatible plugins and dependencies have been removed, including many `PyPI`-provided packages.
- The next major release will be built entirely (or almost entirely) from Anaconda …

Jupyter: update to env py311-250423

---

CHANGES.md
birdhouse/scripts/error-handling.include.sh

If `set` is called without any arguments it prints the current environment to stdout (on most distros). We don't want this, so we only call `set` if there are arguments.
Also makes formatting updates to CHANGES.md
- Bug fix
- none
- 

Fix issue where the current environment is printed to stdout if no shell exec flags are set.

---

birdhouse/components/proxy/backup

Add proxy access log backup.
This should have been added in #532. I'm adding it separately because #532 is so close to being pulled in that I wanted any additional discussion to happen elsewhere.

Add proxy access log backup

---

CHANGES.md
birdhouse/birdhouse-compose.sh

Before, depending on how the `COMPOSE_CONF_LIST` was aggregated / formed by sourcing everything, the output could look like the following: 
```
INFO:     COMPOSE_CONF_LIST=
INFO:     docker-compose.yml
./components/proxy/docker-compose-extra.yml
./components/magpie/docker-compose-extra.yml
./components/magpie/config/proxy/docker-compose-extra.yml
./components/twitcher/docker-compose-extra.yml
./components/twitcher/config/proxy/docker-compose-extra.yml
./components/wps_outputs-volume/docker-compose-extra.yml
./components/wps_outputs-volume/config/proxy/docker-compose-extra.yml
./components/cowbird/docker-compose-extra.yml
./components/cowbird/config/magpie/docker-compose-extra.yml
./components/cowbird/config/proxy/docker-compose-extra.yml
./components/stac/docker-compose-extra.yml …
```

fix empty newlines displayed on `COMPOSE_CONF_LIST`

---

CHANGES.md
birdhouse/optional-components/thanos/docker-compose-extra.yml

Since this container wasn't restarting automatically it could make the entire stack unavailable if it failed.
The proxy container would refuse to start since it could not connect to the upstream thanos-minio server.
- bugfix
- None

Thanos-minio container should always restart on failure
